
		// <global>
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options____global____login
			{
				static public XVar options()
				{
					return new XVar( "captcha", new XVar( "captcha", false ),
"fields", new XVar( "gridFields", XVar.Array(),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar(  ) ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "login_message" ),
"top", new XVar( 0, "login-logo",
1, "login_welcome" ),
"grid", new XVar( 0, "username_label",
1, "username",
2, "password_label",
3, "password",
4, "remember_password",
5, "guest_login" ),
"footer", new XVar( 0, "login_provider",
1, "login_provider1",
2, "login_remind" ),
"superbottom", XVar.Array() ),
"formXtTags", new XVar( "superbottom", XVar.Array() ),
"itemForms", new XVar( "login_message", "above-grid",
"login-logo", "top",
"login_welcome", "top",
"username_label", "grid",
"username", "grid",
"password_label", "grid",
"password", "grid",
"remember_password", "grid",
"guest_login", "grid",
"login_provider", "footer",
"login_provider1", "footer",
"login_remind", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "username_label", new XVar( 0, "username_label" ),
"username", new XVar( 0, "username" ),
"password_label", new XVar( 0, "password_label" ),
"password", new XVar( 0, "password" ),
"login_message", new XVar( 0, "login_message" ),
"guest_login", new XVar( 0, "guest_login" ),
"remember_password", new XVar( 0, "remember_password" ),
"login-logo", new XVar( 0, "login-logo" ),
"login_welcome", new XVar( 0, "login_welcome" ),
"login_remind", new XVar( 0, "login_remind" ),
"login_provider", new XVar( 0, "login_provider",
1, "login_provider1" ) ),
"cellMaps", new XVar(  ) ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "login",
"type", "login",
"layoutId", "pretty1",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "login-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", XVar.Array() ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "login_message" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "plogin-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "login-logo" ) ),
"c2", new XVar( "model", "c2",
"items", XVar.Array() ),
"c3", new XVar( "model", "c3",
"items", new XVar( 0, "login_welcome" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "plogin-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2",
"colspan", 2 ) ),
"section", "" ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "c4" ),
1, new XVar( "cell", "c6" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "username_label",
1, "username" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "password_label",
1, "password" ) ),
"c4", new XVar( "model", "c4",
"items", new XVar( 0, "remember_password" ) ),
"c6", new XVar( "model", "c6",
"items", new XVar( 0, "guest_login" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "plogin-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "login_provider",
1, "login_provider1" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "login_remind" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"superbottom", new XVar( "modelId", "plogin-superbottom",
"grid", XVar.Array(),
"cells", new XVar(  ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "username_label", new XVar( "type", "username_label" ),
"username", new XVar( "type", "username" ),
"password_label", new XVar( "type", "password_label" ),
"password", new XVar( "type", "password" ),
"login_message", new XVar( "type", "login_message" ),
"guest_login", new XVar( "type", "guest_login" ),
"remember_password", new XVar( "type", "remember_password" ),
"login-logo", new XVar( "type", "login-logo",
"font-size", "24px" ),
"login_welcome", new XVar( "type", "login_welcome" ),
"login_remind", new XVar( "type", "login_remind" ),
"login_provider", new XVar( "type", "login_provider",
"providerName", "db" ),
"login_provider1", new XVar( "type", "login_provider",
"providerName", "ad" ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image",
"shadow", false,
"fullSize", true,
"image", new XVar( "image", "auth-login-illustration-light.png",
"source", 2 ) ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "left" );
				}
			}
		}