<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'BSMID',
'MBSMID',
'BANKID',
'PRPID',
'OBLIGEEID',
'PROPNO',
'PROPURUT',
'CNNO',
'REGDATE',
'TTG',
'SDATE',
'EDATE',
'MTUSI',
'SI',
'RATE',
'RATEUNIT',
'MTUPREMI',
'PREMI',
'SECDATE',
'SECUSER',
'SECROLE',
'FLOWSTATUS',
'DISPOSISI',
'TAHUN',
'DAYS',
'SFTURUT',
'STATUS',
'APPRUSER',
'APPRDATE',
'APPRROLE',
'NEEDAPPROV' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'BSMID' => array( 'import_field' ),
'MBSMID' => array( 'import_field1' ),
'BANKID' => array( 'import_field2' ),
'PRPID' => array( 'import_field3' ),
'OBLIGEEID' => array( 'import_field4' ),
'PROPNO' => array( 'import_field5' ),
'PROPURUT' => array( 'import_field6' ),
'CNNO' => array( 'import_field7' ),
'REGDATE' => array( 'import_field8' ),
'TTG' => array( 'import_field9' ),
'SDATE' => array( 'import_field10' ),
'EDATE' => array( 'import_field11' ),
'MTUSI' => array( 'import_field12' ),
'SI' => array( 'import_field13' ),
'RATE' => array( 'import_field14' ),
'RATEUNIT' => array( 'import_field15' ),
'MTUPREMI' => array( 'import_field16' ),
'PREMI' => array( 'import_field17' ),
'SECDATE' => array( 'import_field18' ),
'SECUSER' => array( 'import_field19' ),
'SECROLE' => array( 'import_field20' ),
'FLOWSTATUS' => array( 'import_field21' ),
'DISPOSISI' => array( 'import_field22' ),
'TAHUN' => array( 'import_field23' ),
'DAYS' => array( 'import_field24' ),
'SFTURUT' => array( 'import_field25' ),
'STATUS' => array( 'import_field26' ),
'APPRUSER' => array( 'import_field27' ),
'APPRDATE' => array( 'import_field28' ),
'APPRROLE' => array( 'import_field29' ),
'NEEDAPPROV' => array( 'import_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'BSMID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'MBSMID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'BANKID',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'PRPID',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'OBLIGEEID',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'PROPNO',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'PROPURUT',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'CNNO',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'REGDATE',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'TTG',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'SDATE',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'EDATE',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'MTUSI',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'SI',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'RATE',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'RATEUNIT',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'MTUPREMI',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'PREMI',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'SECDATE',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'SECUSER',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'SECROLE',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'FLOWSTATUS',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'DISPOSISI',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'TAHUN',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'DAYS',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'SFTURUT',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'STATUS',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'APPRUSER',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'APPRDATE',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'APPRROLE',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'NEEDAPPROV',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>