<?php
			$optionsArray = array( 'totals' => array( 'BSMID' => array( 'totalsType' => '' ),
'MBSMID' => array( 'totalsType' => '' ),
'BANKID' => array( 'totalsType' => '' ),
'PRPID' => array( 'totalsType' => '' ),
'OBLIGEEID' => array( 'totalsType' => '' ),
'PROPNO' => array( 'totalsType' => '' ),
'PROPURUT' => array( 'totalsType' => '' ),
'CNNO' => array( 'totalsType' => '' ),
'REGDATE' => array( 'totalsType' => '' ),
'TTG' => array( 'totalsType' => '' ),
'SDATE' => array( 'totalsType' => '' ),
'EDATE' => array( 'totalsType' => '' ),
'MTUSI' => array( 'totalsType' => '' ),
'SI' => array( 'totalsType' => '' ),
'RATE' => array( 'totalsType' => '' ),
'RATEUNIT' => array( 'totalsType' => '' ),
'MTUPREMI' => array( 'totalsType' => '' ),
'PREMI' => array( 'totalsType' => '' ),
'SECDATE' => array( 'totalsType' => '' ),
'SECUSER' => array( 'totalsType' => '' ),
'SECROLE' => array( 'totalsType' => '' ),
'FLOWSTATUS' => array( 'totalsType' => '' ),
'DISPOSISI' => array( 'totalsType' => '' ),
'TAHUN' => array( 'totalsType' => '' ),
'DAYS' => array( 'totalsType' => '' ),
'SFTURUT' => array( 'totalsType' => '' ),
'STATUS' => array( 'totalsType' => '' ),
'APPRUSER' => array( 'totalsType' => '' ),
'APPRDATE' => array( 'totalsType' => '' ),
'APPRROLE' => array( 'totalsType' => '' ),
'NEEDAPPROV' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'BSMID',
'MBSMID',
'BANKID',
'PRPID',
'OBLIGEEID',
'PROPNO',
'PROPURUT',
'CNNO',
'REGDATE',
'TTG',
'SDATE',
'EDATE',
'MTUSI',
'SI',
'RATE',
'RATEUNIT',
'MTUPREMI',
'PREMI',
'SECDATE',
'SECUSER',
'SECROLE',
'FLOWSTATUS',
'DISPOSISI',
'TAHUN',
'DAYS',
'SFTURUT',
'STATUS',
'APPRUSER',
'APPRDATE',
'APPRROLE',
'NEEDAPPROV' ),
'exportFields' => array( 'BSMID',
'MBSMID',
'BANKID',
'PRPID',
'OBLIGEEID',
'PROPNO',
'PROPURUT',
'CNNO',
'REGDATE',
'TTG',
'SDATE',
'EDATE',
'MTUSI',
'SI',
'RATE',
'RATEUNIT',
'MTUPREMI',
'PREMI',
'SECDATE',
'SECUSER',
'SECROLE',
'FLOWSTATUS',
'DISPOSISI',
'TAHUN',
'DAYS',
'SFTURUT',
'STATUS',
'APPRUSER',
'APPRDATE',
'APPRROLE',
'NEEDAPPROV' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'BSMID' => array( 'export_field' ),
'MBSMID' => array( 'export_field1' ),
'BANKID' => array( 'export_field2' ),
'PRPID' => array( 'export_field3' ),
'OBLIGEEID' => array( 'export_field4' ),
'PROPNO' => array( 'export_field5' ),
'PROPURUT' => array( 'export_field6' ),
'CNNO' => array( 'export_field7' ),
'REGDATE' => array( 'export_field8' ),
'TTG' => array( 'export_field9' ),
'SDATE' => array( 'export_field10' ),
'EDATE' => array( 'export_field11' ),
'MTUSI' => array( 'export_field12' ),
'SI' => array( 'export_field13' ),
'RATE' => array( 'export_field14' ),
'RATEUNIT' => array( 'export_field15' ),
'MTUPREMI' => array( 'export_field16' ),
'PREMI' => array( 'export_field17' ),
'SECDATE' => array( 'export_field18' ),
'SECUSER' => array( 'export_field19' ),
'SECROLE' => array( 'export_field20' ),
'FLOWSTATUS' => array( 'export_field21' ),
'DISPOSISI' => array( 'export_field22' ),
'TAHUN' => array( 'export_field23' ),
'DAYS' => array( 'export_field24' ),
'SFTURUT' => array( 'export_field25' ),
'STATUS' => array( 'export_field26' ),
'APPRUSER' => array( 'export_field27' ),
'APPRDATE' => array( 'export_field28' ),
'APPRROLE' => array( 'export_field29' ),
'NEEDAPPROV' => array( 'export_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'BSMID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'MBSMID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'BANKID',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'PRPID',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'OBLIGEEID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'PROPNO',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'PROPURUT',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'CNNO',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'REGDATE',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'TTG',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'SDATE',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'EDATE',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'MTUSI',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'SI',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'RATE',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'RATEUNIT',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'MTUPREMI',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'PREMI',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'SECDATE',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'SECUSER',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'SECROLE',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'FLOWSTATUS',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'DISPOSISI',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'TAHUN',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'DAYS',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'SFTURUT',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'STATUS',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'APPRUSER',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'APPRDATE',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'APPRROLE',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'NEEDAPPROV',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>