
		// dbo.m_employee
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_m_employee_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "m_employee_id", new XVar( "totalsType", "" ),
"NAMA", new XVar( "totalsType", "" ),
"EMAIL", new XVar( "totalsType", "" ),
"POSITION", new XVar( "totalsType", "" ),
"NOREKBCA", new XVar( "totalsType", "" ),
"SECDATE", new XVar( "totalsType", "" ),
"SECUSER", new XVar( "totalsType", "" ),
"GENDER", new XVar( "totalsType", "" ),
"AGAMA", new XVar( "totalsType", "" ),
"BIRTHPLACE", new XVar( "totalsType", "" ),
"BIRTHDAY", new XVar( "totalsType", "" ),
"NOKTP", new XVar( "totalsType", "" ),
"NOKK", new XVar( "totalsType", "" ),
"NOHP", new XVar( "totalsType", "" ),
"EMAILPRIBADI", new XVar( "totalsType", "" ),
"ALAMATKTP", new XVar( "totalsType", "" ),
"ALAMATDOM", new XVar( "totalsType", "" ),
"PRID", new XVar( "totalsType", "" ),
"COMID", new XVar( "totalsType", "" ),
"NIK", new XVar( "totalsType", "" ),
"DATEJOIN", new XVar( "totalsType", "" ),
"DATEANGKAT", new XVar( "totalsType", "" ),
"NONPWP", new XVar( "totalsType", "" ),
"NPBJPSKES", new XVar( "totalsType", "" ),
"NOBPJSTK", new XVar( "totalsType", "" ),
"NOPASPOR", new XVar( "totalsType", "" ),
"STATUSTAX", new XVar( "totalsType", "" ),
"DARURATNAMA", new XVar( "totalsType", "" ),
"DARURATHUB", new XVar( "totalsType", "" ),
"DARURATTELP", new XVar( "totalsType", "" ),
"USERID", new XVar( "totalsType", "" ),
"LEVEL", new XVar( "totalsType", "" ),
"UPRID", new XVar( "totalsType", "" ),
"STATUSKAWIN", new XVar( "totalsType", "" ),
"JMLANAK", new XVar( "totalsType", "" ),
"NOASURANSI", new XVar( "totalsType", "" ),
"NOPKS", new XVar( "totalsType", "" ),
"DPKS", new XVar( "totalsType", "" ),
"HANDLER", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "m_employee_id",
1, "PRID",
2, "COMID",
3, "NIK",
4, "NAMA",
5, "EMAIL",
6, "POSITION",
7, "NOREKBCA",
8, "SECDATE",
9, "SECUSER",
10, "GENDER",
11, "AGAMA",
12, "BIRTHPLACE",
13, "BIRTHDAY",
14, "NOKTP",
15, "NOKK",
16, "NOHP",
17, "EMAILPRIBADI",
18, "ALAMATKTP",
19, "ALAMATDOM",
20, "DATEJOIN",
21, "DATEANGKAT",
22, "NONPWP",
23, "NPBJPSKES",
24, "NOBPJSTK",
25, "NOPASPOR",
26, "STATUSTAX",
27, "DARURATNAMA",
28, "DARURATHUB",
29, "DARURATTELP",
30, "USERID",
31, "LEVEL",
32, "UPRID",
33, "STATUSKAWIN",
34, "JMLANAK",
35, "NOASURANSI",
36, "NOPKS",
37, "DPKS",
38, "HANDLER" ),
"exportFields", new XVar( 0, "m_employee_id",
1, "NAMA",
2, "EMAIL",
3, "POSITION",
4, "NOREKBCA",
5, "SECDATE",
6, "SECUSER",
7, "GENDER",
8, "AGAMA",
9, "BIRTHPLACE",
10, "BIRTHDAY",
11, "NOKTP",
12, "NOKK",
13, "NOHP",
14, "EMAILPRIBADI",
15, "ALAMATKTP",
16, "ALAMATDOM",
17, "PRID",
18, "COMID",
19, "NIK",
20, "DATEJOIN",
21, "DATEANGKAT",
22, "NONPWP",
23, "NPBJPSKES",
24, "NOBPJSTK",
25, "NOPASPOR",
26, "STATUSTAX",
27, "DARURATNAMA",
28, "DARURATHUB",
29, "DARURATTELP",
30, "USERID",
31, "LEVEL",
32, "UPRID",
33, "STATUSKAWIN",
34, "JMLANAK",
35, "NOASURANSI",
36, "NOPKS",
37, "DPKS",
38, "HANDLER" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "m_employee_id", new XVar( 0, "export_field" ),
"PRID", new XVar( 0, "export_field1" ),
"COMID", new XVar( 0, "export_field2" ),
"NIK", new XVar( 0, "export_field3" ),
"NAMA", new XVar( 0, "export_field4" ),
"EMAIL", new XVar( 0, "export_field5" ),
"POSITION", new XVar( 0, "export_field6" ),
"NOREKBCA", new XVar( 0, "export_field7" ),
"SECDATE", new XVar( 0, "export_field8" ),
"SECUSER", new XVar( 0, "export_field9" ),
"GENDER", new XVar( 0, "export_field10" ),
"AGAMA", new XVar( 0, "export_field11" ),
"BIRTHPLACE", new XVar( 0, "export_field12" ),
"BIRTHDAY", new XVar( 0, "export_field13" ),
"NOKTP", new XVar( 0, "export_field14" ),
"NOKK", new XVar( 0, "export_field15" ),
"NOHP", new XVar( 0, "export_field16" ),
"EMAILPRIBADI", new XVar( 0, "export_field17" ),
"ALAMATKTP", new XVar( 0, "export_field18" ),
"ALAMATDOM", new XVar( 0, "export_field19" ),
"DATEJOIN", new XVar( 0, "export_field20" ),
"DATEANGKAT", new XVar( 0, "export_field21" ),
"NONPWP", new XVar( 0, "export_field22" ),
"NPBJPSKES", new XVar( 0, "export_field23" ),
"NOBPJSTK", new XVar( 0, "export_field24" ),
"NOPASPOR", new XVar( 0, "export_field25" ),
"STATUSTAX", new XVar( 0, "export_field26" ),
"DARURATNAMA", new XVar( 0, "export_field27" ),
"DARURATHUB", new XVar( 0, "export_field28" ),
"DARURATTELP", new XVar( 0, "export_field29" ),
"USERID", new XVar( 0, "export_field30" ),
"LEVEL", new XVar( 0, "export_field31" ),
"UPRID", new XVar( 0, "export_field32" ),
"STATUSKAWIN", new XVar( 0, "export_field33" ),
"JMLANAK", new XVar( 0, "export_field34" ),
"NOASURANSI", new XVar( 0, "export_field35" ),
"NOPKS", new XVar( 0, "export_field36" ),
"DPKS", new XVar( 0, "export_field37" ),
"HANDLER", new XVar( 0, "export_field38" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field4",
2, "export_field5",
3, "export_field6",
4, "export_field7",
5, "export_field8",
6, "export_field9",
7, "export_field10",
8, "export_field11",
9, "export_field12",
10, "export_field13",
11, "export_field14",
12, "export_field15",
13, "export_field16",
14, "export_field17",
15, "export_field18",
16, "export_field19",
17, "export_field1",
18, "export_field2",
19, "export_field3",
20, "export_field20",
21, "export_field21",
22, "export_field22",
23, "export_field23",
24, "export_field24",
25, "export_field25",
26, "export_field26",
27, "export_field27",
28, "export_field28",
29, "export_field29",
30, "export_field30",
31, "export_field31",
32, "export_field32",
33, "export_field33",
34, "export_field34",
35, "export_field35",
36, "export_field36",
37, "export_field37",
38, "export_field38" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_field11", "grid",
"export_field12", "grid",
"export_field13", "grid",
"export_field14", "grid",
"export_field15", "grid",
"export_field16", "grid",
"export_field17", "grid",
"export_field18", "grid",
"export_field19", "grid",
"export_field1", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field20", "grid",
"export_field21", "grid",
"export_field22", "grid",
"export_field23", "grid",
"export_field24", "grid",
"export_field25", "grid",
"export_field26", "grid",
"export_field27", "grid",
"export_field28", "grid",
"export_field29", "grid",
"export_field30", "grid",
"export_field31", "grid",
"export_field32", "grid",
"export_field33", "grid",
"export_field34", "grid",
"export_field35", "grid",
"export_field36", "grid",
"export_field37", "grid",
"export_field38", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field12",
13, "export_field13",
14, "export_field14",
15, "export_field15",
16, "export_field16",
17, "export_field17",
18, "export_field18",
19, "export_field19",
20, "export_field20",
21, "export_field21",
22, "export_field22",
23, "export_field23",
24, "export_field24",
25, "export_field25",
26, "export_field26",
27, "export_field27",
28, "export_field28",
29, "export_field29",
30, "export_field30",
31, "export_field31",
32, "export_field32",
33, "export_field33",
34, "export_field34",
35, "export_field35",
36, "export_field36",
37, "export_field37",
38, "export_field38" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field4",
2, "export_field5",
3, "export_field6",
4, "export_field7",
5, "export_field8",
6, "export_field9",
7, "export_field10",
8, "export_field11",
9, "export_field12",
10, "export_field13",
11, "export_field14",
12, "export_field15",
13, "export_field16",
14, "export_field17",
15, "export_field18",
16, "export_field19",
17, "export_field1",
18, "export_field2",
19, "export_field3",
20, "export_field20",
21, "export_field21",
22, "export_field22",
23, "export_field23",
24, "export_field24",
25, "export_field25",
26, "export_field26",
27, "export_field27",
28, "export_field28",
29, "export_field29",
30, "export_field30",
31, "export_field31",
32, "export_field32",
33, "export_field33",
34, "export_field34",
35, "export_field35",
36, "export_field36",
37, "export_field37",
38, "export_field38" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "m_employee_id",
"type", "export_field" ),
"export_field1", new XVar( "field", "PRID",
"type", "export_field" ),
"export_field2", new XVar( "field", "COMID",
"type", "export_field" ),
"export_field3", new XVar( "field", "NIK",
"type", "export_field" ),
"export_field4", new XVar( "field", "NAMA",
"type", "export_field" ),
"export_field5", new XVar( "field", "EMAIL",
"type", "export_field" ),
"export_field6", new XVar( "field", "POSITION",
"type", "export_field" ),
"export_field7", new XVar( "field", "NOREKBCA",
"type", "export_field" ),
"export_field8", new XVar( "field", "SECDATE",
"type", "export_field" ),
"export_field9", new XVar( "field", "SECUSER",
"type", "export_field" ),
"export_field10", new XVar( "field", "GENDER",
"type", "export_field" ),
"export_field11", new XVar( "field", "AGAMA",
"type", "export_field" ),
"export_field12", new XVar( "field", "BIRTHPLACE",
"type", "export_field" ),
"export_field13", new XVar( "field", "BIRTHDAY",
"type", "export_field" ),
"export_field14", new XVar( "field", "NOKTP",
"type", "export_field" ),
"export_field15", new XVar( "field", "NOKK",
"type", "export_field" ),
"export_field16", new XVar( "field", "NOHP",
"type", "export_field" ),
"export_field17", new XVar( "field", "EMAILPRIBADI",
"type", "export_field" ),
"export_field18", new XVar( "field", "ALAMATKTP",
"type", "export_field" ),
"export_field19", new XVar( "field", "ALAMATDOM",
"type", "export_field" ),
"export_field20", new XVar( "field", "DATEJOIN",
"type", "export_field" ),
"export_field21", new XVar( "field", "DATEANGKAT",
"type", "export_field" ),
"export_field22", new XVar( "field", "NONPWP",
"type", "export_field" ),
"export_field23", new XVar( "field", "NPBJPSKES",
"type", "export_field" ),
"export_field24", new XVar( "field", "NOBPJSTK",
"type", "export_field" ),
"export_field25", new XVar( "field", "NOPASPOR",
"type", "export_field" ),
"export_field26", new XVar( "field", "STATUSTAX",
"type", "export_field" ),
"export_field27", new XVar( "field", "DARURATNAMA",
"type", "export_field" ),
"export_field28", new XVar( "field", "DARURATHUB",
"type", "export_field" ),
"export_field29", new XVar( "field", "DARURATTELP",
"type", "export_field" ),
"export_field30", new XVar( "field", "USERID",
"type", "export_field" ),
"export_field31", new XVar( "field", "LEVEL",
"type", "export_field" ),
"export_field32", new XVar( "field", "UPRID",
"type", "export_field" ),
"export_field33", new XVar( "field", "STATUSKAWIN",
"type", "export_field" ),
"export_field34", new XVar( "field", "JMLANAK",
"type", "export_field" ),
"export_field35", new XVar( "field", "NOASURANSI",
"type", "export_field" ),
"export_field36", new XVar( "field", "NOPKS",
"type", "export_field" ),
"export_field37", new XVar( "field", "DPKS",
"type", "export_field" ),
"export_field38", new XVar( "field", "HANDLER",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}