
		// dbo.m_employee
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_m_employee_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "m_employee_id",
1, "NAMA",
2, "EMAIL",
3, "POSITION",
4, "NOREKBCA",
5, "SECDATE",
6, "SECUSER",
7, "GENDER",
8, "AGAMA",
9, "BIRTHPLACE",
10, "BIRTHDAY",
11, "NOKTP",
12, "NOKK",
13, "NOHP",
14, "EMAILPRIBADI",
15, "ALAMATKTP",
16, "ALAMATDOM",
17, "PRID",
18, "COMID",
19, "NIK",
20, "DATEJOIN",
21, "DATEANGKAT",
22, "NONPWP",
23, "NPBJPSKES",
24, "NOBPJSTK",
25, "NOPASPOR",
26, "STATUSTAX",
27, "DARURATNAMA",
28, "DARURATHUB",
29, "DARURATTELP",
30, "USERID",
31, "LEVEL",
32, "UPRID",
33, "STATUSKAWIN",
34, "JMLANAK",
35, "NOASURANSI",
36, "NOPKS",
37, "DPKS",
38, "HANDLER" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "m_employee_id", new XVar( 0, "import_field" ),
"PRID", new XVar( 0, "import_field1" ),
"COMID", new XVar( 0, "import_field2" ),
"NIK", new XVar( 0, "import_field3" ),
"NAMA", new XVar( 0, "import_field4" ),
"EMAIL", new XVar( 0, "import_field5" ),
"POSITION", new XVar( 0, "import_field6" ),
"NOREKBCA", new XVar( 0, "import_field7" ),
"SECDATE", new XVar( 0, "import_field8" ),
"SECUSER", new XVar( 0, "import_field9" ),
"GENDER", new XVar( 0, "import_field10" ),
"AGAMA", new XVar( 0, "import_field11" ),
"BIRTHPLACE", new XVar( 0, "import_field12" ),
"BIRTHDAY", new XVar( 0, "import_field13" ),
"NOKTP", new XVar( 0, "import_field14" ),
"NOKK", new XVar( 0, "import_field15" ),
"NOHP", new XVar( 0, "import_field16" ),
"EMAILPRIBADI", new XVar( 0, "import_field17" ),
"ALAMATKTP", new XVar( 0, "import_field18" ),
"ALAMATDOM", new XVar( 0, "import_field19" ),
"DATEJOIN", new XVar( 0, "import_field20" ),
"DATEANGKAT", new XVar( 0, "import_field21" ),
"NONPWP", new XVar( 0, "import_field22" ),
"NPBJPSKES", new XVar( 0, "import_field23" ),
"NOBPJSTK", new XVar( 0, "import_field24" ),
"NOPASPOR", new XVar( 0, "import_field25" ),
"STATUSTAX", new XVar( 0, "import_field26" ),
"DARURATNAMA", new XVar( 0, "import_field27" ),
"DARURATHUB", new XVar( 0, "import_field28" ),
"DARURATTELP", new XVar( 0, "import_field29" ),
"USERID", new XVar( 0, "import_field30" ),
"LEVEL", new XVar( 0, "import_field31" ),
"UPRID", new XVar( 0, "import_field32" ),
"STATUSKAWIN", new XVar( 0, "import_field33" ),
"JMLANAK", new XVar( 0, "import_field34" ),
"NOASURANSI", new XVar( 0, "import_field35" ),
"NOPKS", new XVar( 0, "import_field36" ),
"DPKS", new XVar( 0, "import_field37" ),
"HANDLER", new XVar( 0, "import_field38" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field4",
2, "import_field5",
3, "import_field6",
4, "import_field7",
5, "import_field8",
6, "import_field9",
7, "import_field10",
8, "import_field11",
9, "import_field12",
10, "import_field13",
11, "import_field14",
12, "import_field15",
13, "import_field16",
14, "import_field17",
15, "import_field18",
16, "import_field19",
17, "import_field1",
18, "import_field2",
19, "import_field3",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid",
"import_field16", "grid",
"import_field17", "grid",
"import_field18", "grid",
"import_field19", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field20", "grid",
"import_field21", "grid",
"import_field22", "grid",
"import_field23", "grid",
"import_field24", "grid",
"import_field25", "grid",
"import_field26", "grid",
"import_field27", "grid",
"import_field28", "grid",
"import_field29", "grid",
"import_field30", "grid",
"import_field31", "grid",
"import_field32", "grid",
"import_field33", "grid",
"import_field34", "grid",
"import_field35", "grid",
"import_field36", "grid",
"import_field37", "grid",
"import_field38", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field4",
2, "import_field5",
3, "import_field6",
4, "import_field7",
5, "import_field8",
6, "import_field9",
7, "import_field10",
8, "import_field11",
9, "import_field12",
10, "import_field13",
11, "import_field14",
12, "import_field15",
13, "import_field16",
14, "import_field17",
15, "import_field18",
16, "import_field19",
17, "import_field1",
18, "import_field2",
19, "import_field3",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "m_employee_id",
"type", "import_field" ),
"import_field1", new XVar( "field", "PRID",
"type", "import_field" ),
"import_field2", new XVar( "field", "COMID",
"type", "import_field" ),
"import_field3", new XVar( "field", "NIK",
"type", "import_field" ),
"import_field4", new XVar( "field", "NAMA",
"type", "import_field" ),
"import_field5", new XVar( "field", "EMAIL",
"type", "import_field" ),
"import_field6", new XVar( "field", "POSITION",
"type", "import_field" ),
"import_field7", new XVar( "field", "NOREKBCA",
"type", "import_field" ),
"import_field8", new XVar( "field", "SECDATE",
"type", "import_field" ),
"import_field9", new XVar( "field", "SECUSER",
"type", "import_field" ),
"import_field10", new XVar( "field", "GENDER",
"type", "import_field" ),
"import_field11", new XVar( "field", "AGAMA",
"type", "import_field" ),
"import_field12", new XVar( "field", "BIRTHPLACE",
"type", "import_field" ),
"import_field13", new XVar( "field", "BIRTHDAY",
"type", "import_field" ),
"import_field14", new XVar( "field", "NOKTP",
"type", "import_field" ),
"import_field15", new XVar( "field", "NOKK",
"type", "import_field" ),
"import_field16", new XVar( "field", "NOHP",
"type", "import_field" ),
"import_field17", new XVar( "field", "EMAILPRIBADI",
"type", "import_field" ),
"import_field18", new XVar( "field", "ALAMATKTP",
"type", "import_field" ),
"import_field19", new XVar( "field", "ALAMATDOM",
"type", "import_field" ),
"import_field20", new XVar( "field", "DATEJOIN",
"type", "import_field" ),
"import_field21", new XVar( "field", "DATEANGKAT",
"type", "import_field" ),
"import_field22", new XVar( "field", "NONPWP",
"type", "import_field" ),
"import_field23", new XVar( "field", "NPBJPSKES",
"type", "import_field" ),
"import_field24", new XVar( "field", "NOBPJSTK",
"type", "import_field" ),
"import_field25", new XVar( "field", "NOPASPOR",
"type", "import_field" ),
"import_field26", new XVar( "field", "STATUSTAX",
"type", "import_field" ),
"import_field27", new XVar( "field", "DARURATNAMA",
"type", "import_field" ),
"import_field28", new XVar( "field", "DARURATHUB",
"type", "import_field" ),
"import_field29", new XVar( "field", "DARURATTELP",
"type", "import_field" ),
"import_field30", new XVar( "field", "USERID",
"type", "import_field" ),
"import_field31", new XVar( "field", "LEVEL",
"type", "import_field" ),
"import_field32", new XVar( "field", "UPRID",
"type", "import_field" ),
"import_field33", new XVar( "field", "STATUSKAWIN",
"type", "import_field" ),
"import_field34", new XVar( "field", "JMLANAK",
"type", "import_field" ),
"import_field35", new XVar( "field", "NOASURANSI",
"type", "import_field" ),
"import_field36", new XVar( "field", "NOPKS",
"type", "import_field" ),
"import_field37", new XVar( "field", "DPKS",
"type", "import_field" ),
"import_field38", new XVar( "field", "HANDLER",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right" );
				}
			}
		}