
		// dbo.m_employee
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_m_employee_search
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "m_employee_id",
1, "PRID",
2, "COMID",
3, "NIK",
4, "NAMA",
5, "EMAIL",
6, "POSITION",
7, "NOREKBCA",
8, "SECDATE",
9, "SECUSER",
10, "GENDER",
11, "AGAMA",
12, "BIRTHPLACE",
13, "BIRTHDAY",
14, "NOKTP",
15, "NOKK",
16, "NOHP",
17, "EMAILPRIBADI",
18, "ALAMATKTP",
19, "ALAMATDOM",
20, "DATEJOIN",
21, "DATEANGKAT",
22, "NONPWP",
23, "NPBJPSKES",
24, "NOBPJSTK",
25, "NOPASPOR",
26, "STATUSTAX",
27, "DARURATNAMA",
28, "DARURATHUB",
29, "DARURATTELP",
30, "USERID",
31, "LEVEL",
32, "UPRID",
33, "STATUSKAWIN",
34, "JMLANAK",
35, "NOASURANSI",
36, "NOPKS",
37, "DPKS",
38, "HANDLER" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "m_employee_id", new XVar( 0, "integrated_search_field" ),
"PRID", new XVar( 0, "integrated_search_field1" ),
"COMID", new XVar( 0, "integrated_search_field2" ),
"NIK", new XVar( 0, "integrated_search_field3" ),
"NAMA", new XVar( 0, "integrated_search_field4" ),
"EMAIL", new XVar( 0, "integrated_search_field5" ),
"POSITION", new XVar( 0, "integrated_search_field6" ),
"NOREKBCA", new XVar( 0, "integrated_search_field7" ),
"SECDATE", new XVar( 0, "integrated_search_field8" ),
"SECUSER", new XVar( 0, "integrated_search_field9" ),
"GENDER", new XVar( 0, "integrated_search_field10" ),
"AGAMA", new XVar( 0, "integrated_search_field11" ),
"BIRTHPLACE", new XVar( 0, "integrated_search_field12" ),
"BIRTHDAY", new XVar( 0, "integrated_search_field13" ),
"NOKTP", new XVar( 0, "integrated_search_field14" ),
"NOKK", new XVar( 0, "integrated_search_field15" ),
"NOHP", new XVar( 0, "integrated_search_field16" ),
"EMAILPRIBADI", new XVar( 0, "integrated_search_field17" ),
"ALAMATKTP", new XVar( 0, "integrated_search_field18" ),
"ALAMATDOM", new XVar( 0, "integrated_search_field19" ),
"DATEJOIN", new XVar( 0, "integrated_search_field20" ),
"DATEANGKAT", new XVar( 0, "integrated_search_field21" ),
"NONPWP", new XVar( 0, "integrated_search_field22" ),
"NPBJPSKES", new XVar( 0, "integrated_search_field23" ),
"NOBPJSTK", new XVar( 0, "integrated_search_field24" ),
"NOPASPOR", new XVar( 0, "integrated_search_field25" ),
"STATUSTAX", new XVar( 0, "integrated_search_field26" ),
"DARURATNAMA", new XVar( 0, "integrated_search_field27" ),
"DARURATHUB", new XVar( 0, "integrated_search_field28" ),
"DARURATTELP", new XVar( 0, "integrated_search_field29" ),
"USERID", new XVar( 0, "integrated_search_field30" ),
"LEVEL", new XVar( 0, "integrated_search_field31" ),
"UPRID", new XVar( 0, "integrated_search_field32" ),
"STATUSKAWIN", new XVar( 0, "integrated_search_field33" ),
"JMLANAK", new XVar( 0, "integrated_search_field34" ),
"NOASURANSI", new XVar( 0, "integrated_search_field35" ),
"NOPKS", new XVar( 0, "integrated_search_field36" ),
"DPKS", new XVar( 0, "integrated_search_field37" ),
"HANDLER", new XVar( 0, "integrated_search_field38" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ),
"top", new XVar( 0, "search_header" ),
"grid", new XVar( 0, "integrated_search_field",
1, "integrated_search_field4",
2, "integrated_search_field5",
3, "integrated_search_field6",
4, "integrated_search_field7",
5, "integrated_search_field8",
6, "integrated_search_field9",
7, "integrated_search_field10",
8, "integrated_search_field11",
9, "integrated_search_field12",
10, "integrated_search_field13",
11, "integrated_search_field14",
12, "integrated_search_field15",
13, "integrated_search_field16",
14, "integrated_search_field17",
15, "integrated_search_field18",
16, "integrated_search_field19",
17, "integrated_search_field1",
18, "integrated_search_field2",
19, "integrated_search_field3",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "search_search", "below-grid",
"search_reset", "below-grid",
"search_back_list", "below-grid",
"search_cancel", "below-grid",
"search_header", "top",
"integrated_search_field", "grid",
"integrated_search_field4", "grid",
"integrated_search_field5", "grid",
"integrated_search_field6", "grid",
"integrated_search_field7", "grid",
"integrated_search_field8", "grid",
"integrated_search_field9", "grid",
"integrated_search_field10", "grid",
"integrated_search_field11", "grid",
"integrated_search_field12", "grid",
"integrated_search_field13", "grid",
"integrated_search_field14", "grid",
"integrated_search_field15", "grid",
"integrated_search_field16", "grid",
"integrated_search_field17", "grid",
"integrated_search_field18", "grid",
"integrated_search_field19", "grid",
"integrated_search_field1", "grid",
"integrated_search_field2", "grid",
"integrated_search_field3", "grid",
"integrated_search_field20", "grid",
"integrated_search_field21", "grid",
"integrated_search_field22", "grid",
"integrated_search_field23", "grid",
"integrated_search_field24", "grid",
"integrated_search_field25", "grid",
"integrated_search_field26", "grid",
"integrated_search_field27", "grid",
"integrated_search_field28", "grid",
"integrated_search_field29", "grid",
"integrated_search_field30", "grid",
"integrated_search_field31", "grid",
"integrated_search_field32", "grid",
"integrated_search_field33", "grid",
"integrated_search_field34", "grid",
"integrated_search_field35", "grid",
"integrated_search_field36", "grid",
"integrated_search_field37", "grid",
"integrated_search_field38", "grid" ),
"itemLocations", new XVar( "integrated_search_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field38", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "search_header", new XVar( 0, "search_header" ),
"search_reset", new XVar( 0, "search_reset" ),
"search_back_list", new XVar( 0, "search_back_list" ),
"search_search", new XVar( 0, "search_search" ),
"search_cancel", new XVar( 0, "search_cancel" ),
"integrated_search_field", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field4",
2, "integrated_search_field5",
3, "integrated_search_field6",
4, "integrated_search_field7",
5, "integrated_search_field8",
6, "integrated_search_field9",
7, "integrated_search_field10",
8, "integrated_search_field11",
9, "integrated_search_field12",
10, "integrated_search_field13",
11, "integrated_search_field14",
12, "integrated_search_field15",
13, "integrated_search_field16",
14, "integrated_search_field17",
15, "integrated_search_field18",
16, "integrated_search_field19",
17, "integrated_search_field1",
18, "integrated_search_field2",
19, "integrated_search_field3",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"misc", new XVar( "type", "search",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "search",
"type", "search",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "search-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "search-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "search-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-search",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field4",
2, "integrated_search_field5",
3, "integrated_search_field6",
4, "integrated_search_field7",
5, "integrated_search_field8",
6, "integrated_search_field9",
7, "integrated_search_field10",
8, "integrated_search_field11",
9, "integrated_search_field12",
10, "integrated_search_field13",
11, "integrated_search_field14",
12, "integrated_search_field15",
13, "integrated_search_field16",
14, "integrated_search_field17",
15, "integrated_search_field18",
16, "integrated_search_field19",
17, "integrated_search_field1",
18, "integrated_search_field2",
19, "integrated_search_field3",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38" ) ) ),
"deferredItems", XVar.Array(),
"separateLabels", false ) ),
"items", new XVar( "search_header", new XVar( "type", "search_header" ),
"search_reset", new XVar( "type", "search_reset" ),
"search_back_list", new XVar( "type", "search_back_list" ),
"search_search", new XVar( "type", "search_search" ),
"search_cancel", new XVar( "type", "search_cancel" ),
"integrated_search_field", new XVar( "field", "m_employee_id",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field1", new XVar( "field", "PRID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field2", new XVar( "field", "COMID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field3", new XVar( "field", "NIK",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field4", new XVar( "field", "NAMA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field5", new XVar( "field", "EMAIL",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field6", new XVar( "field", "POSITION",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field7", new XVar( "field", "NOREKBCA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field8", new XVar( "field", "SECDATE",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field9", new XVar( "field", "SECUSER",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field10", new XVar( "field", "GENDER",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field11", new XVar( "field", "AGAMA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field12", new XVar( "field", "BIRTHPLACE",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field13", new XVar( "field", "BIRTHDAY",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field14", new XVar( "field", "NOKTP",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field15", new XVar( "field", "NOKK",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field16", new XVar( "field", "NOHP",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field17", new XVar( "field", "EMAILPRIBADI",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field18", new XVar( "field", "ALAMATKTP",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field19", new XVar( "field", "ALAMATDOM",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field20", new XVar( "field", "DATEJOIN",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field21", new XVar( "field", "DATEANGKAT",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field22", new XVar( "field", "NONPWP",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field23", new XVar( "field", "NPBJPSKES",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field24", new XVar( "field", "NOBPJSTK",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field25", new XVar( "field", "NOPASPOR",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field26", new XVar( "field", "STATUSTAX",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field27", new XVar( "field", "DARURATNAMA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field28", new XVar( "field", "DARURATHUB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field29", new XVar( "field", "DARURATTELP",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field30", new XVar( "field", "USERID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field31", new XVar( "field", "LEVEL",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field32", new XVar( "field", "UPRID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field33", new XVar( "field", "STATUSKAWIN",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field34", new XVar( "field", "JMLANAK",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field35", new XVar( "field", "NOASURANSI",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field36", new XVar( "field", "NOPKS",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field37", new XVar( "field", "DPKS",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field38", new XVar( "field", "HANDLER",
"type", "integrated_search_field",
"orientation", 0,
"required", false ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right" );
				}
			}
		}