<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PLCID',
'PPLCID',
'MPLCID',
'RPLCID',
'BSMID',
'KODECAB',
'MKTNO',
'MKTURUT',
'PLCNO',
'URUTNO',
'QSNO',
'QSURUT',
'CANO',
'CAURUT',
'SFTNO',
'ENDSNO',
'OBLIGEEID',
'BANKID',
'PLCTTG',
'MKTDATE',
'PLCDATE',
'SDATE',
'EDATE',
'STATUSCLOSE',
'POLICYTYPE',
'DAYSNUM',
'DAYSBASIS',
'ISTBA',
'ISEXCLUSIVE',
'REFFNO',
'STATUS',
'IDBS',
'KODESHARIA',
'SECDATE',
'SECUSER',
'SECROLE' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PLCID' => array( 'import_field' ),
'PPLCID' => array( 'import_field1' ),
'MPLCID' => array( 'import_field2' ),
'RPLCID' => array( 'import_field3' ),
'BSMID' => array( 'import_field4' ),
'KODECAB' => array( 'import_field5' ),
'MKTNO' => array( 'import_field6' ),
'MKTURUT' => array( 'import_field7' ),
'PLCNO' => array( 'import_field8' ),
'URUTNO' => array( 'import_field9' ),
'QSNO' => array( 'import_field10' ),
'QSURUT' => array( 'import_field11' ),
'CANO' => array( 'import_field12' ),
'CAURUT' => array( 'import_field13' ),
'SFTNO' => array( 'import_field14' ),
'ENDSNO' => array( 'import_field15' ),
'OBLIGEEID' => array( 'import_field16' ),
'BANKID' => array( 'import_field17' ),
'PLCTTG' => array( 'import_field18' ),
'MKTDATE' => array( 'import_field19' ),
'PLCDATE' => array( 'import_field20' ),
'SDATE' => array( 'import_field21' ),
'EDATE' => array( 'import_field22' ),
'STATUSCLOSE' => array( 'import_field23' ),
'POLICYTYPE' => array( 'import_field24' ),
'DAYSNUM' => array( 'import_field25' ),
'DAYSBASIS' => array( 'import_field26' ),
'ISTBA' => array( 'import_field27' ),
'ISEXCLUSIVE' => array( 'import_field28' ),
'REFFNO' => array( 'import_field29' ),
'STATUS' => array( 'import_field30' ),
'IDBS' => array( 'import_field31' ),
'KODESHARIA' => array( 'import_field32' ),
'SECDATE' => array( 'import_field33' ),
'SECUSER' => array( 'import_field34' ),
'SECROLE' => array( 'import_field35' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PLCID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PPLCID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'MPLCID',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'RPLCID',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'BSMID',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'KODECAB',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'MKTNO',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'MKTURUT',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'PLCNO',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'URUTNO',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'QSNO',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'QSURUT',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'CANO',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'CAURUT',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'SFTNO',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'ENDSNO',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'OBLIGEEID',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'BANKID',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'PLCTTG',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'MKTDATE',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'PLCDATE',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'SDATE',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'EDATE',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'STATUSCLOSE',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'POLICYTYPE',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'DAYSNUM',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'DAYSBASIS',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'ISTBA',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'ISEXCLUSIVE',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'REFFNO',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'STATUS',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'IDBS',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'KODESHARIA',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'SECDATE',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'SECUSER',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'SECROLE',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>