<?php
			$optionsArray = array( 'totals' => array( 'PLCID' => array( 'totalsType' => '' ),
'PPLCID' => array( 'totalsType' => '' ),
'MPLCID' => array( 'totalsType' => '' ),
'RPLCID' => array( 'totalsType' => '' ),
'BSMID' => array( 'totalsType' => '' ),
'KODECAB' => array( 'totalsType' => '' ),
'MKTNO' => array( 'totalsType' => '' ),
'MKTURUT' => array( 'totalsType' => '' ),
'PLCNO' => array( 'totalsType' => '' ),
'URUTNO' => array( 'totalsType' => '' ),
'QSNO' => array( 'totalsType' => '' ),
'QSURUT' => array( 'totalsType' => '' ),
'CANO' => array( 'totalsType' => '' ),
'CAURUT' => array( 'totalsType' => '' ),
'SFTNO' => array( 'totalsType' => '' ),
'ENDSNO' => array( 'totalsType' => '' ),
'OBLIGEEID' => array( 'totalsType' => '' ),
'BANKID' => array( 'totalsType' => '' ),
'PLCTTG' => array( 'totalsType' => '' ),
'MKTDATE' => array( 'totalsType' => '' ),
'PLCDATE' => array( 'totalsType' => '' ),
'SDATE' => array( 'totalsType' => '' ),
'EDATE' => array( 'totalsType' => '' ),
'STATUSCLOSE' => array( 'totalsType' => '' ),
'POLICYTYPE' => array( 'totalsType' => '' ),
'DAYSNUM' => array( 'totalsType' => '' ),
'DAYSBASIS' => array( 'totalsType' => '' ),
'ISTBA' => array( 'totalsType' => '' ),
'ISEXCLUSIVE' => array( 'totalsType' => '' ),
'REFFNO' => array( 'totalsType' => '' ),
'STATUS' => array( 'totalsType' => '' ),
'IDBS' => array( 'totalsType' => '' ),
'KODESHARIA' => array( 'totalsType' => '' ),
'SECDATE' => array( 'totalsType' => '' ),
'SECUSER' => array( 'totalsType' => '' ),
'SECROLE' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PLCID',
'PPLCID',
'MPLCID',
'RPLCID',
'BSMID',
'KODECAB',
'MKTNO',
'MKTURUT',
'PLCNO',
'URUTNO',
'QSNO',
'QSURUT',
'CANO',
'CAURUT',
'SFTNO',
'ENDSNO',
'OBLIGEEID',
'BANKID',
'PLCTTG',
'MKTDATE',
'PLCDATE',
'SDATE',
'EDATE',
'STATUSCLOSE',
'POLICYTYPE',
'DAYSNUM',
'DAYSBASIS',
'ISTBA',
'ISEXCLUSIVE',
'REFFNO',
'STATUS',
'IDBS',
'KODESHARIA',
'SECDATE',
'SECUSER',
'SECROLE' ),
'exportFields' => array( 'PLCID',
'PPLCID',
'MPLCID',
'RPLCID',
'BSMID',
'KODECAB',
'MKTNO',
'MKTURUT',
'PLCNO',
'URUTNO',
'QSNO',
'QSURUT',
'CANO',
'CAURUT',
'SFTNO',
'ENDSNO',
'OBLIGEEID',
'BANKID',
'PLCTTG',
'MKTDATE',
'PLCDATE',
'SDATE',
'EDATE',
'STATUSCLOSE',
'POLICYTYPE',
'DAYSNUM',
'DAYSBASIS',
'ISTBA',
'ISEXCLUSIVE',
'REFFNO',
'STATUS',
'IDBS',
'KODESHARIA',
'SECDATE',
'SECUSER',
'SECROLE' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PLCID' => array( 'export_field' ),
'PPLCID' => array( 'export_field1' ),
'MPLCID' => array( 'export_field2' ),
'RPLCID' => array( 'export_field3' ),
'BSMID' => array( 'export_field4' ),
'KODECAB' => array( 'export_field5' ),
'MKTNO' => array( 'export_field6' ),
'MKTURUT' => array( 'export_field7' ),
'PLCNO' => array( 'export_field8' ),
'URUTNO' => array( 'export_field9' ),
'QSNO' => array( 'export_field10' ),
'QSURUT' => array( 'export_field11' ),
'CANO' => array( 'export_field12' ),
'CAURUT' => array( 'export_field13' ),
'SFTNO' => array( 'export_field14' ),
'ENDSNO' => array( 'export_field15' ),
'OBLIGEEID' => array( 'export_field16' ),
'BANKID' => array( 'export_field17' ),
'PLCTTG' => array( 'export_field18' ),
'MKTDATE' => array( 'export_field19' ),
'PLCDATE' => array( 'export_field20' ),
'SDATE' => array( 'export_field21' ),
'EDATE' => array( 'export_field22' ),
'STATUSCLOSE' => array( 'export_field23' ),
'POLICYTYPE' => array( 'export_field24' ),
'DAYSNUM' => array( 'export_field25' ),
'DAYSBASIS' => array( 'export_field26' ),
'ISTBA' => array( 'export_field27' ),
'ISEXCLUSIVE' => array( 'export_field28' ),
'REFFNO' => array( 'export_field29' ),
'STATUS' => array( 'export_field30' ),
'IDBS' => array( 'export_field31' ),
'KODESHARIA' => array( 'export_field32' ),
'SECDATE' => array( 'export_field33' ),
'SECUSER' => array( 'export_field34' ),
'SECROLE' => array( 'export_field35' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PLCID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PPLCID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'MPLCID',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'RPLCID',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'BSMID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'KODECAB',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'MKTNO',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'MKTURUT',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'PLCNO',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'URUTNO',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'QSNO',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'QSURUT',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'CANO',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'CAURUT',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'SFTNO',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'ENDSNO',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'OBLIGEEID',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'BANKID',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'PLCTTG',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'MKTDATE',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'PLCDATE',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'SDATE',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'EDATE',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'STATUSCLOSE',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'POLICYTYPE',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'DAYSNUM',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'DAYSBASIS',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'ISTBA',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'ISEXCLUSIVE',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'REFFNO',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'STATUS',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'IDBS',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'KODESHARIA',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'SECDATE',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'SECUSER',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'SECROLE',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>