
		// dbo.t_visitor_log
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_t_visitor_log_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "t_visitor_log_name",
1, "t_visitor_log_company",
2, "t_visitor_log_time_in",
3, "t_visitor_log_time_out",
4, "t_visitor_log_images",
5, "t_visitor_log_owner",
6, "t_visitor_log_room_id",
7, "t_visitor_log_location_id" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "t_visitor_log_location_id", new XVar( 0, "import_field" ),
"t_visitor_log_name", new XVar( 0, "import_field1" ),
"t_visitor_log_company", new XVar( 0, "import_field2" ),
"t_visitor_log_time_in", new XVar( 0, "import_field3" ),
"t_visitor_log_time_out", new XVar( 0, "import_field4" ),
"t_visitor_log_images", new XVar( 0, "import_field5" ),
"t_visitor_log_owner", new XVar( 0, "import_field6" ),
"t_visitor_log_room_id", new XVar( 0, "import_field7" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field1",
1, "import_field2",
2, "import_field3",
3, "import_field4",
4, "import_field5",
5, "import_field6",
6, "import_field7",
7, "import_field" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field1",
1, "import_field2",
2, "import_field3",
3, "import_field4",
4, "import_field5",
5, "import_field6",
6, "import_field7",
7, "import_field" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "t_visitor_log_location_id",
"type", "import_field" ),
"import_field1", new XVar( "field", "t_visitor_log_name",
"type", "import_field" ),
"import_field2", new XVar( "field", "t_visitor_log_company",
"type", "import_field" ),
"import_field3", new XVar( "field", "t_visitor_log_time_in",
"type", "import_field" ),
"import_field4", new XVar( "field", "t_visitor_log_time_out",
"type", "import_field" ),
"import_field5", new XVar( "field", "t_visitor_log_images",
"type", "import_field" ),
"import_field6", new XVar( "field", "t_visitor_log_owner",
"type", "import_field" ),
"import_field7", new XVar( "field", "t_visitor_log_room_id",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right" );
				}
			}
		}