
		// dbo.t_visitor_log
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_t_visitor_log_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "t_visitor_log_id", new XVar( "totalsType", "" ),
"t_visitor_log_name", new XVar( "totalsType", "" ),
"t_visitor_log_company", new XVar( "totalsType", "" ),
"t_visitor_log_location_id", new XVar( "totalsType", "" ),
"t_visitor_log_time_in", new XVar( "totalsType", "" ),
"t_visitor_log_time_out", new XVar( "totalsType", "" ),
"t_visitor_log_images", new XVar( "totalsType", "" ),
"t_visitor_log_owner", new XVar( "totalsType", "" ),
"t_visitor_log_room_id", new XVar( "totalsType", "" ),
"add_user", new XVar( "totalsType", "" ),
"add_date", new XVar( "totalsType", "" ),
"edit_user", new XVar( "totalsType", "" ),
"edit_date", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "t_visitor_log_location_id",
1, "t_visitor_log_name",
2, "t_visitor_log_company",
3, "t_visitor_log_time_in",
4, "t_visitor_log_time_out",
5, "t_visitor_log_images",
6, "t_visitor_log_owner",
7, "t_visitor_log_room_id" ),
"exportFields", new XVar( 0, "t_visitor_log_name",
1, "t_visitor_log_company",
2, "t_visitor_log_time_in",
3, "t_visitor_log_time_out",
4, "t_visitor_log_images",
5, "t_visitor_log_owner",
6, "t_visitor_log_room_id",
7, "t_visitor_log_location_id" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "t_visitor_log_location_id", new XVar( 0, "export_field" ),
"t_visitor_log_name", new XVar( 0, "export_field1" ),
"t_visitor_log_company", new XVar( 0, "export_field2" ),
"t_visitor_log_time_in", new XVar( 0, "export_field3" ),
"t_visitor_log_time_out", new XVar( 0, "export_field4" ),
"t_visitor_log_images", new XVar( 0, "export_field5" ),
"t_visitor_log_owner", new XVar( 0, "export_field6" ),
"t_visitor_log_room_id", new XVar( 0, "export_field7" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field1",
1, "export_field2",
2, "export_field3",
3, "export_field4",
4, "export_field5",
5, "export_field6",
6, "export_field7",
7, "export_field" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field1", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field1",
1, "export_field2",
2, "export_field3",
3, "export_field4",
4, "export_field5",
5, "export_field6",
6, "export_field7",
7, "export_field" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "t_visitor_log_location_id",
"type", "export_field" ),
"export_field1", new XVar( "field", "t_visitor_log_name",
"type", "export_field" ),
"export_field2", new XVar( "field", "t_visitor_log_company",
"type", "export_field" ),
"export_field3", new XVar( "field", "t_visitor_log_time_in",
"type", "export_field" ),
"export_field4", new XVar( "field", "t_visitor_log_time_out",
"type", "export_field" ),
"export_field5", new XVar( "field", "t_visitor_log_images",
"type", "export_field" ),
"export_field6", new XVar( "field", "t_visitor_log_owner",
"type", "export_field" ),
"export_field7", new XVar( "field", "t_visitor_log_room_id",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}