
		// dbo.t_visitor_log
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_t_visitor_log_add
			{
				static public XVar options()
				{
					return new XVar( "captcha", new XVar( "captcha", false ),
"fields", new XVar( "gridFields", new XVar( 0, "t_visitor_log_name",
1, "t_visitor_log_company",
2, "t_visitor_log_location_id",
3, "t_visitor_log_time_in",
4, "t_visitor_log_time_out",
5, "t_visitor_log_images",
6, "t_visitor_log_owner",
7, "t_visitor_log_room_id" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "t_visitor_log_name", new XVar( 0, "integrated_edit_field1" ),
"t_visitor_log_company", new XVar( 0, "integrated_edit_field2" ),
"t_visitor_log_location_id", new XVar( 0, "integrated_edit_field3" ),
"t_visitor_log_time_in", new XVar( 0, "integrated_edit_field4" ),
"t_visitor_log_time_out", new XVar( 0, "integrated_edit_field5" ),
"t_visitor_log_images", new XVar( 0, "integrated_edit_field6" ),
"t_visitor_log_owner", new XVar( 0, "integrated_edit_field7" ),
"t_visitor_log_room_id", new XVar( 0, "integrated_edit_field8" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "add_message" ),
"below-grid", new XVar( 0, "add_save",
1, "add_reset",
2, "add_back_list",
3, "add_cancel" ),
"top", new XVar( 0, "add_header" ),
"grid", new XVar( 0, "integrated_edit_field1",
1, "integrated_edit_field2",
2, "integrated_edit_field7",
3, "integrated_edit_field8",
4, "integrated_edit_field5",
5, "integrated_edit_field6",
6, "integrated_edit_field3",
7, "integrated_edit_field4" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "message_block" ) ),
"itemForms", new XVar( "add_message", "above-grid",
"add_save", "below-grid",
"add_reset", "below-grid",
"add_back_list", "below-grid",
"add_cancel", "below-grid",
"add_header", "top",
"integrated_edit_field1", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field4", "grid" ),
"itemLocations", new XVar( "integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c10" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c11" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c13" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c14" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c15" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "add_header", new XVar( 0, "add_header" ),
"add_back_list", new XVar( 0, "add_back_list" ),
"add_cancel", new XVar( 0, "add_cancel" ),
"add_message", new XVar( 0, "add_message" ),
"add_save", new XVar( 0, "add_save" ),
"add_reset", new XVar( 0, "add_reset" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field1",
1, "integrated_edit_field2",
2, "integrated_edit_field3",
3, "integrated_edit_field4",
4, "integrated_edit_field5",
5, "integrated_edit_field6",
6, "integrated_edit_field7",
7, "integrated_edit_field8" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c14", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c15", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c12", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c13", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c10", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c11", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field8" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false ),
"misc", new XVar( "type", "add",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "add",
"type", "add",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "add-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_message" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "add-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_save",
1, "add_reset",
2, "add_back_list",
3, "add_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "add-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c" ) ),
"section", "" ),
1, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c14" ),
1, new XVar( "cell", "c15" ) ) ),
2, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c12" ),
1, new XVar( "cell", "c13" ) ) ),
3, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c10" ),
1, new XVar( "cell", "c11" ) ) ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field1" ) ),
"c", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field2" ) ),
"c10", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field7" ) ),
"c11", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field8" ) ),
"c12", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field5" ) ),
"c13", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field6" ) ),
"c14", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field3" ) ),
"c15", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field4" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "add_header", new XVar( "type", "add_header" ),
"add_back_list", new XVar( "type", "add_back_list" ),
"add_cancel", new XVar( "type", "add_cancel" ),
"add_message", new XVar( "type", "add_message" ),
"add_save", new XVar( "type", "add_save" ),
"add_reset", new XVar( "type", "add_reset" ),
"integrated_edit_field1", new XVar( "field", "t_visitor_log_name",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "t_visitor_log_company",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "t_visitor_log_location_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "t_visitor_log_time_in",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "t_visitor_log_time_out",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "t_visitor_log_images",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "t_visitor_log_owner",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field8", new XVar( "field", "t_visitor_log_room_id",
"type", "integrated_edit_field",
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 11,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right" );
				}
			}
		}