using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_admin_users
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["admin_users"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".ShortName"] = "admin_users";
			tdataArray["admin_users"][".OwnerID"] = "";
			tdataArray["admin_users"][".OriginalTable"] = "dbo.m_login";
			tdataArray["admin_users"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["admin_users"][".originalPagesByType"] = tdataArray["admin_users"][".pagesByType"];
			tdataArray["admin_users"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["admin_users"][".originalPages"] = tdataArray["admin_users"][".pages"];
			tdataArray["admin_users"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["admin_users"][".originalDefaultPages"] = tdataArray["admin_users"][".defaultPages"];
			fieldLabelsArray["admin_users"] = SettingsMap.GetArray();
			fieldToolTipsArray["admin_users"] = SettingsMap.GetArray();
			pageTitlesArray["admin_users"] = SettingsMap.GetArray();
			placeHoldersArray["admin_users"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["admin_users"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["admin_users"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["admin_users"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["admin_users"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["admin_users"]["English"]["login_id"] = "Login Id";
				fieldToolTipsArray["admin_users"]["English"]["login_id"] = "";
				placeHoldersArray["admin_users"]["English"]["login_id"] = "";
				fieldLabelsArray["admin_users"]["English"]["username"] = "Username";
				fieldToolTipsArray["admin_users"]["English"]["username"] = "";
				placeHoldersArray["admin_users"]["English"]["username"] = "";
				fieldLabelsArray["admin_users"]["English"]["password"] = "Password";
				fieldToolTipsArray["admin_users"]["English"]["password"] = "";
				placeHoldersArray["admin_users"]["English"]["password"] = "";
				fieldLabelsArray["admin_users"]["English"]["fullname"] = "Fullname";
				fieldToolTipsArray["admin_users"]["English"]["fullname"] = "";
				placeHoldersArray["admin_users"]["English"]["fullname"] = "";
				fieldLabelsArray["admin_users"]["English"]["email"] = "Email";
				fieldToolTipsArray["admin_users"]["English"]["email"] = "";
				placeHoldersArray["admin_users"]["English"]["email"] = "";
				fieldLabelsArray["admin_users"]["English"]["isactive"] = "Isactive";
				fieldToolTipsArray["admin_users"]["English"]["isactive"] = "";
				placeHoldersArray["admin_users"]["English"]["isactive"] = "";
				fieldLabelsArray["admin_users"]["English"]["add_user"] = "Add User";
				fieldToolTipsArray["admin_users"]["English"]["add_user"] = "";
				placeHoldersArray["admin_users"]["English"]["add_user"] = "";
				fieldLabelsArray["admin_users"]["English"]["add_date"] = "Add Date";
				fieldToolTipsArray["admin_users"]["English"]["add_date"] = "";
				placeHoldersArray["admin_users"]["English"]["add_date"] = "";
				fieldLabelsArray["admin_users"]["English"]["edit_user"] = "Edit User";
				fieldToolTipsArray["admin_users"]["English"]["edit_user"] = "";
				placeHoldersArray["admin_users"]["English"]["edit_user"] = "";
				fieldLabelsArray["admin_users"]["English"]["edit_date"] = "Edit Date";
				fieldToolTipsArray["admin_users"]["English"]["edit_date"] = "";
				placeHoldersArray["admin_users"]["English"]["edit_date"] = "";
				fieldLabelsArray["admin_users"]["English"]["userpic"] = "Userpic";
				fieldToolTipsArray["admin_users"]["English"]["userpic"] = "";
				placeHoldersArray["admin_users"]["English"]["userpic"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["admin_users"]["English"])))
				{
					tdataArray["admin_users"][".isUseToolTips"] = true;
				}
			}
			tdataArray["admin_users"][".NCSearch"] = true;
			tdataArray["admin_users"][".shortTableName"] = "admin_users";
			tdataArray["admin_users"][".nSecOptions"] = 0;
			tdataArray["admin_users"][".mainTableOwnerID"] = "";
			tdataArray["admin_users"][".entityType"] = 1;
			tdataArray["admin_users"][".connId"] = "TSUNDB_at_alpha_talisman_co_id";
			tdataArray["admin_users"][".strOriginalTableName"] = "dbo.m_login";
			tdataArray["admin_users"][".showAddInPopup"] = false;
			tdataArray["admin_users"][".showEditInPopup"] = false;
			tdataArray["admin_users"][".showViewInPopup"] = false;
			tdataArray["admin_users"][".listAjax"] = false;
			tdataArray["admin_users"][".audit"] = true;
			tdataArray["admin_users"][".locking"] = false;
			GlobalVars.pages = tdataArray["admin_users"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["admin_users"][".edit"] = true;
				tdataArray["admin_users"][".afterEditAction"] = 1;
				tdataArray["admin_users"][".closePopupAfterEdit"] = 1;
				tdataArray["admin_users"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["admin_users"][".add"] = true;
				tdataArray["admin_users"][".afterAddAction"] = 1;
				tdataArray["admin_users"][".closePopupAfterAdd"] = 1;
				tdataArray["admin_users"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["admin_users"][".list"] = true;
			}
			tdataArray["admin_users"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["admin_users"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["admin_users"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["admin_users"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["admin_users"][".printFriendly"] = true;
			}
			tdataArray["admin_users"][".showSimpleSearchOptions"] = true;
			tdataArray["admin_users"][".allowShowHideFields"] = true;
			tdataArray["admin_users"][".allowFieldsReordering"] = true;
			tdataArray["admin_users"][".isUseAjaxSuggest"] = true;


			tdataArray["admin_users"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["admin_users"][".buttonsAdded"] = false;
			tdataArray["admin_users"][".addPageEvents"] = false;
			tdataArray["admin_users"][".isUseTimeForSearch"] = false;
			tdataArray["admin_users"][".badgeColor"] = "008B8B";
			tdataArray["admin_users"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".googleLikeFields"].Add("login_id");
			tdataArray["admin_users"][".googleLikeFields"].Add("username");
			tdataArray["admin_users"][".googleLikeFields"].Add("password");
			tdataArray["admin_users"][".googleLikeFields"].Add("fullname");
			tdataArray["admin_users"][".googleLikeFields"].Add("email");
			tdataArray["admin_users"][".googleLikeFields"].Add("isactive");
			tdataArray["admin_users"][".googleLikeFields"].Add("add_user");
			tdataArray["admin_users"][".googleLikeFields"].Add("add_date");
			tdataArray["admin_users"][".googleLikeFields"].Add("edit_user");
			tdataArray["admin_users"][".googleLikeFields"].Add("edit_date");
			tdataArray["admin_users"][".tableType"] = "list";
			tdataArray["admin_users"][".printerPageOrientation"] = 0;
			tdataArray["admin_users"][".nPrinterPageScale"] = 100;
			tdataArray["admin_users"][".nPrinterSplitRecords"] = 40;
			tdataArray["admin_users"][".geocodingEnabled"] = false;
			tdataArray["admin_users"][".pageSize"] = 20;
			tdataArray["admin_users"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["admin_users"][".strOrderBy"] = tstrOrderBy;
			tdataArray["admin_users"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".sqlHead"] = "SELECT login_id,  	username,  	password,  	fullname,  	email,  	isactive,  	add_user,  	add_date,  	edit_user,  	edit_date,  	userpic";
			tdataArray["admin_users"][".sqlFrom"] = "FROM dbo.m_login";
			tdataArray["admin_users"][".sqlWhereExpr"] = "";
			tdataArray["admin_users"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["admin_users"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["admin_users"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["admin_users"][".highlightSearchResults"] = true;
			tableKeysArray["admin_users"] = SettingsMap.GetArray();
			tableKeysArray["admin_users"].Add("login_id");
			tdataArray["admin_users"][".Keys"] = tableKeysArray["admin_users"];
			tdataArray["admin_users"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "login_id";
			fdata["GoodName"] = "login_id";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","login_id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "login_id";
			fdata["sourceSingle"] = "login_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "login_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["login_id"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("login_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "username";
			fdata["GoodName"] = "username";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","username");
			fdata["FieldType"] = 202;
			fdata["strField"] = "username";
			fdata["sourceSingle"] = "username";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "username";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["username"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("username");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "password";
			fdata["GoodName"] = "password";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","password");
			fdata["FieldType"] = 202;
			fdata["strField"] = "password";
			fdata["sourceSingle"] = "password";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "password";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["password"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("password");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "fullname";
			fdata["GoodName"] = "fullname";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","fullname");
			fdata["FieldType"] = 202;
			fdata["strField"] = "fullname";
			fdata["sourceSingle"] = "fullname";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "fullname";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["fullname"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("fullname");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","email");
			fdata["FieldType"] = 202;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["email"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "isactive";
			fdata["GoodName"] = "isactive";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","isactive");
			fdata["FieldType"] = 3;
			fdata["strField"] = "isactive";
			fdata["sourceSingle"] = "isactive";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "isactive";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["isactive"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("isactive");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "add_user";
			fdata["GoodName"] = "add_user";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","add_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "add_user";
			fdata["sourceSingle"] = "add_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["add_user"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("add_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "add_date";
			fdata["GoodName"] = "add_date";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","add_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "add_date";
			fdata["sourceSingle"] = "add_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["add_date"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("add_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "edit_user";
			fdata["GoodName"] = "edit_user";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","edit_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "edit_user";
			fdata["sourceSingle"] = "edit_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["edit_user"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("edit_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "edit_date";
			fdata["GoodName"] = "edit_date";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","edit_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "edit_date";
			fdata["sourceSingle"] = "edit_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["edit_date"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("edit_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "userpic";
			fdata["GoodName"] = "userpic";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","userpic");
			fdata["FieldType"] = 205;
			fdata["strField"] = "userpic";
			fdata["sourceSingle"] = "userpic";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "userpic";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Database Image");
			vdata["ImageWidth"] = 600;
			vdata["ImageHeight"] = 400;
			vdata["showGallery"] = true;
			vdata["galleryMode"] = 2;
			vdata["captionMode"] = 1;
			vdata["captionField"] = "";
			vdata["imageBorder"] = 1;
			vdata["imageFullWidth"] = 1;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Database image");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "NOT Empty";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["userpic"] = fdata;
			GlobalVars.tables_data["admin_users"] = tdataArray["admin_users"];
			GlobalVars.field_labels["admin_users"] = fieldLabelsArray["admin_users"];
			GlobalVars.fieldToolTips["admin_users"] = fieldToolTipsArray["admin_users"];
			GlobalVars.placeHolders["admin_users"] = placeHoldersArray["admin_users"];
			GlobalVars.page_titles["admin_users"] = pageTitlesArray["admin_users"];
			CommonFunctions.changeTextControlsToDate(new XVar("admin_users"));
			GlobalVars.detailsTablesData["admin_users"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["admin_users"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "login_id,  	username,  	password,  	fullname,  	email,  	isactive,  	add_user,  	add_date,  	edit_user,  	edit_date,  	userpic";
protoArray["0"]["m_strFrom"] = "FROM dbo.m_login";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "login_id", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["6"]["m_sql"] = "login_id";
protoArray["6"]["m_srcTableName"] = "admin_users";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "username", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["8"]["m_sql"] = "username";
protoArray["8"]["m_srcTableName"] = "admin_users";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "password", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["10"]["m_sql"] = "password";
protoArray["10"]["m_srcTableName"] = "admin_users";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "fullname", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["12"]["m_sql"] = "fullname";
protoArray["12"]["m_srcTableName"] = "admin_users";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["14"]["m_sql"] = "email";
protoArray["14"]["m_srcTableName"] = "admin_users";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "isactive", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["16"]["m_sql"] = "isactive";
protoArray["16"]["m_srcTableName"] = "admin_users";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_user", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["18"]["m_sql"] = "add_user";
protoArray["18"]["m_srcTableName"] = "admin_users";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_date", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["20"]["m_sql"] = "add_date";
protoArray["20"]["m_srcTableName"] = "admin_users";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_user", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["22"]["m_sql"] = "edit_user";
protoArray["22"]["m_srcTableName"] = "admin_users";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_date", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["24"]["m_sql"] = "edit_date";
protoArray["24"]["m_srcTableName"] = "admin_users";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "userpic", "m_strTable", "dbo.m_login", "m_srcTableName", "admin_users"));

protoArray["26"]["m_sql"] = "userpic";
protoArray["26"]["m_srcTableName"] = "admin_users";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["28"] = SettingsMap.GetArray();
protoArray["28"]["m_link"] = "SQLL_MAIN";
protoArray["29"] = SettingsMap.GetArray();
protoArray["29"]["m_strName"] = "dbo.m_login";
protoArray["29"]["m_srcTableName"] = "admin_users";
protoArray["29"]["m_columns"] = SettingsMap.GetArray();
protoArray["29"]["m_columns"].Add("login_id");
protoArray["29"]["m_columns"].Add("username");
protoArray["29"]["m_columns"].Add("password");
protoArray["29"]["m_columns"].Add("fullname");
protoArray["29"]["m_columns"].Add("email");
protoArray["29"]["m_columns"].Add("isactive");
protoArray["29"]["m_columns"].Add("add_user");
protoArray["29"]["m_columns"].Add("add_date");
protoArray["29"]["m_columns"].Add("edit_user");
protoArray["29"]["m_columns"].Add("edit_date");
protoArray["29"]["m_columns"].Add("userpic");
protoArray["29"]["m_columns"].Add("ext_security_id");
obj = new SQLTable(protoArray["29"]);

protoArray["28"]["m_table"] = obj;
protoArray["28"]["m_sql"] = "dbo.m_login";
protoArray["28"]["m_alias"] = "";
protoArray["28"]["m_srcTableName"] = "admin_users";
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_sql"] = "";
protoArray["30"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["30"]["m_column"] = obj;
protoArray["30"]["m_contained"] = SettingsMap.GetArray();
protoArray["30"]["m_strCase"] = "";
protoArray["30"]["m_havingmode"] = false;
protoArray["30"]["m_inBrackets"] = false;
protoArray["30"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["30"]);

protoArray["28"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["28"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "admin_users";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["admin_users"] = obj;

				
		
			tdataArray["admin_users"][".sqlquery"] = queryData_Array["admin_users"];
			tdataArray["admin_users"][".hasEvents"] = false;
			GlobalVars.tables_data["admin_users"] = tdataArray["admin_users"];
		}
	}

}
