using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_m_login
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["m_login"] = SettingsMap.GetArray();
			tdataArray["m_login"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["m_login"][".ShortName"] = "m_login";
			tdataArray["m_login"][".OwnerID"] = "";
			tdataArray["m_login"][".OriginalTable"] = "dbo.m_login";
			tdataArray["m_login"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["m_login"][".originalPagesByType"] = tdataArray["m_login"][".pagesByType"];
			tdataArray["m_login"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["m_login"][".originalPages"] = tdataArray["m_login"][".pages"];
			tdataArray["m_login"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["m_login"][".originalDefaultPages"] = tdataArray["m_login"][".defaultPages"];
			fieldLabelsArray["m_login"] = SettingsMap.GetArray();
			fieldToolTipsArray["m_login"] = SettingsMap.GetArray();
			pageTitlesArray["m_login"] = SettingsMap.GetArray();
			placeHoldersArray["m_login"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["m_login"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["m_login"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["m_login"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["m_login"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["m_login"]["English"]["login_id"] = "Login Id";
				fieldToolTipsArray["m_login"]["English"]["login_id"] = "";
				placeHoldersArray["m_login"]["English"]["login_id"] = "";
				fieldLabelsArray["m_login"]["English"]["username"] = "Username";
				fieldToolTipsArray["m_login"]["English"]["username"] = "";
				placeHoldersArray["m_login"]["English"]["username"] = "";
				fieldLabelsArray["m_login"]["English"]["password"] = "Password";
				fieldToolTipsArray["m_login"]["English"]["password"] = "";
				placeHoldersArray["m_login"]["English"]["password"] = "";
				fieldLabelsArray["m_login"]["English"]["fullname"] = "Fullname";
				fieldToolTipsArray["m_login"]["English"]["fullname"] = "";
				placeHoldersArray["m_login"]["English"]["fullname"] = "";
				fieldLabelsArray["m_login"]["English"]["email"] = "Email";
				fieldToolTipsArray["m_login"]["English"]["email"] = "";
				placeHoldersArray["m_login"]["English"]["email"] = "";
				fieldLabelsArray["m_login"]["English"]["isactive"] = "Isactive";
				fieldToolTipsArray["m_login"]["English"]["isactive"] = "";
				placeHoldersArray["m_login"]["English"]["isactive"] = "";
				fieldLabelsArray["m_login"]["English"]["add_user"] = "Add User";
				fieldToolTipsArray["m_login"]["English"]["add_user"] = "";
				placeHoldersArray["m_login"]["English"]["add_user"] = "";
				fieldLabelsArray["m_login"]["English"]["add_date"] = "Add Date";
				fieldToolTipsArray["m_login"]["English"]["add_date"] = "";
				placeHoldersArray["m_login"]["English"]["add_date"] = "";
				fieldLabelsArray["m_login"]["English"]["edit_user"] = "Edit User";
				fieldToolTipsArray["m_login"]["English"]["edit_user"] = "";
				placeHoldersArray["m_login"]["English"]["edit_user"] = "";
				fieldLabelsArray["m_login"]["English"]["edit_date"] = "Edit Date";
				fieldToolTipsArray["m_login"]["English"]["edit_date"] = "";
				placeHoldersArray["m_login"]["English"]["edit_date"] = "";
				fieldLabelsArray["m_login"]["English"]["userpic"] = "Userpic";
				fieldToolTipsArray["m_login"]["English"]["userpic"] = "";
				placeHoldersArray["m_login"]["English"]["userpic"] = "";
				fieldLabelsArray["m_login"]["English"]["ext_security_id"] = "Ext Security Id";
				fieldToolTipsArray["m_login"]["English"]["ext_security_id"] = "";
				placeHoldersArray["m_login"]["English"]["ext_security_id"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["m_login"]["English"])))
				{
					tdataArray["m_login"][".isUseToolTips"] = true;
				}
			}
			tdataArray["m_login"][".NCSearch"] = true;
			tdataArray["m_login"][".shortTableName"] = "m_login";
			tdataArray["m_login"][".nSecOptions"] = 0;
			tdataArray["m_login"][".mainTableOwnerID"] = "";
			tdataArray["m_login"][".entityType"] = 0;
			tdataArray["m_login"][".connId"] = "TSUNDB_at_alpha_talisman_co_id";
			tdataArray["m_login"][".strOriginalTableName"] = "dbo.m_login";
			tdataArray["m_login"][".showAddInPopup"] = false;
			tdataArray["m_login"][".showEditInPopup"] = false;
			tdataArray["m_login"][".showViewInPopup"] = false;
			tdataArray["m_login"][".listAjax"] = false;
			tdataArray["m_login"][".audit"] = true;
			tdataArray["m_login"][".locking"] = false;
			GlobalVars.pages = tdataArray["m_login"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["m_login"][".edit"] = true;
				tdataArray["m_login"][".afterEditAction"] = 1;
				tdataArray["m_login"][".closePopupAfterEdit"] = 1;
				tdataArray["m_login"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["m_login"][".add"] = true;
				tdataArray["m_login"][".afterAddAction"] = 1;
				tdataArray["m_login"][".closePopupAfterAdd"] = 1;
				tdataArray["m_login"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["m_login"][".list"] = true;
			}
			tdataArray["m_login"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["m_login"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["m_login"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["m_login"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["m_login"][".printFriendly"] = true;
			}
			tdataArray["m_login"][".showSimpleSearchOptions"] = true;
			tdataArray["m_login"][".allowShowHideFields"] = true;
			tdataArray["m_login"][".allowFieldsReordering"] = true;
			tdataArray["m_login"][".isUseAjaxSuggest"] = true;


			tdataArray["m_login"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["m_login"][".buttonsAdded"] = false;
			tdataArray["m_login"][".addPageEvents"] = false;
			tdataArray["m_login"][".isUseTimeForSearch"] = false;
			tdataArray["m_login"][".badgeColor"] = "DAA520";
			tdataArray["m_login"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["m_login"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["m_login"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["m_login"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["m_login"][".googleLikeFields"].Add("login_id");
			tdataArray["m_login"][".googleLikeFields"].Add("username");
			tdataArray["m_login"][".googleLikeFields"].Add("password");
			tdataArray["m_login"][".googleLikeFields"].Add("fullname");
			tdataArray["m_login"][".googleLikeFields"].Add("email");
			tdataArray["m_login"][".googleLikeFields"].Add("isactive");
			tdataArray["m_login"][".googleLikeFields"].Add("add_user");
			tdataArray["m_login"][".googleLikeFields"].Add("add_date");
			tdataArray["m_login"][".googleLikeFields"].Add("edit_user");
			tdataArray["m_login"][".googleLikeFields"].Add("edit_date");
			tdataArray["m_login"][".tableType"] = "list";
			tdataArray["m_login"][".printerPageOrientation"] = 0;
			tdataArray["m_login"][".nPrinterPageScale"] = 100;
			tdataArray["m_login"][".nPrinterSplitRecords"] = 40;
			tdataArray["m_login"][".geocodingEnabled"] = false;
			tdataArray["m_login"][".isDisplayLoading"] = true;
			tdataArray["m_login"][".pageSize"] = 20;
			tdataArray["m_login"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["m_login"][".strOrderBy"] = tstrOrderBy;
			tdataArray["m_login"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["m_login"][".sqlHead"] = "SELECT login_id,  	username,  	password,  	fullname,  	email,  	isactive,  	add_user,  	add_date,  	edit_user,  	edit_date,  	userpic,  	ext_security_id";
			tdataArray["m_login"][".sqlFrom"] = "FROM dbo.m_login";
			tdataArray["m_login"][".sqlWhereExpr"] = "";
			tdataArray["m_login"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["m_login"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["m_login"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["m_login"][".highlightSearchResults"] = true;
			tableKeysArray["m_login"] = SettingsMap.GetArray();
			tableKeysArray["m_login"].Add("login_id");
			tdataArray["m_login"][".Keys"] = tableKeysArray["m_login"];
			tdataArray["m_login"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "login_id";
			fdata["GoodName"] = "login_id";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","login_id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "login_id";
			fdata["sourceSingle"] = "login_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "login_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["login_id"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("login_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "username";
			fdata["GoodName"] = "username";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","username");
			fdata["FieldType"] = 202;
			fdata["strField"] = "username";
			fdata["sourceSingle"] = "username";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "username";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["username"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("username");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "password";
			fdata["GoodName"] = "password";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","password");
			fdata["FieldType"] = 202;
			fdata["strField"] = "password";
			fdata["sourceSingle"] = "password";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "password";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["password"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("password");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "fullname";
			fdata["GoodName"] = "fullname";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","fullname");
			fdata["FieldType"] = 202;
			fdata["strField"] = "fullname";
			fdata["sourceSingle"] = "fullname";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "fullname";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["fullname"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("fullname");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","email");
			fdata["FieldType"] = 202;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["email"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "isactive";
			fdata["GoodName"] = "isactive";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","isactive");
			fdata["FieldType"] = 3;
			fdata["strField"] = "isactive";
			fdata["sourceSingle"] = "isactive";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "isactive";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["isactive"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("isactive");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "add_user";
			fdata["GoodName"] = "add_user";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","add_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "add_user";
			fdata["sourceSingle"] = "add_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["add_user"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("add_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "add_date";
			fdata["GoodName"] = "add_date";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","add_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "add_date";
			fdata["sourceSingle"] = "add_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["add_date"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("add_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "edit_user";
			fdata["GoodName"] = "edit_user";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","edit_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "edit_user";
			fdata["sourceSingle"] = "edit_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["edit_user"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("edit_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "edit_date";
			fdata["GoodName"] = "edit_date";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","edit_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "edit_date";
			fdata["sourceSingle"] = "edit_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["edit_date"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("edit_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "userpic";
			fdata["GoodName"] = "userpic";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","userpic");
			fdata["FieldType"] = 205;
			fdata["strField"] = "userpic";
			fdata["sourceSingle"] = "userpic";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "userpic";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Database Image");
			vdata["ImageWidth"] = 600;
			vdata["ImageHeight"] = 400;
			vdata["showGallery"] = true;
			vdata["galleryMode"] = 2;
			vdata["captionMode"] = 1;
			vdata["captionField"] = "";
			vdata["imageBorder"] = 1;
			vdata["imageFullWidth"] = 1;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Database image");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "NOT Empty";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["userpic"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "ext_security_id";
			fdata["GoodName"] = "ext_security_id";
			fdata["ownerTable"] = "dbo.m_login";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_m_login","ext_security_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "ext_security_id";
			fdata["sourceSingle"] = "ext_security_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ext_security_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["m_login"]["ext_security_id"] = fdata;
			tdataArray["m_login"][".searchableFields"].Add("ext_security_id");
			GlobalVars.tables_data["dbo.m_login"] = tdataArray["m_login"];
			GlobalVars.field_labels["dbo_m_login"] = fieldLabelsArray["m_login"];
			GlobalVars.fieldToolTips["dbo_m_login"] = fieldToolTipsArray["m_login"];
			GlobalVars.placeHolders["dbo_m_login"] = placeHoldersArray["m_login"];
			GlobalVars.page_titles["dbo_m_login"] = pageTitlesArray["m_login"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.m_login"));
			GlobalVars.detailsTablesData["dbo.m_login"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.m_login"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "login_id,  	username,  	password,  	fullname,  	email,  	isactive,  	add_user,  	add_date,  	edit_user,  	edit_date,  	userpic,  	ext_security_id";
protoArray["0"]["m_strFrom"] = "FROM dbo.m_login";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "login_id", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["6"]["m_sql"] = "login_id";
protoArray["6"]["m_srcTableName"] = "dbo.m_login";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "username", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["8"]["m_sql"] = "username";
protoArray["8"]["m_srcTableName"] = "dbo.m_login";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "password", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["10"]["m_sql"] = "password";
protoArray["10"]["m_srcTableName"] = "dbo.m_login";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "fullname", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["12"]["m_sql"] = "fullname";
protoArray["12"]["m_srcTableName"] = "dbo.m_login";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["14"]["m_sql"] = "email";
protoArray["14"]["m_srcTableName"] = "dbo.m_login";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "isactive", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["16"]["m_sql"] = "isactive";
protoArray["16"]["m_srcTableName"] = "dbo.m_login";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_user", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["18"]["m_sql"] = "add_user";
protoArray["18"]["m_srcTableName"] = "dbo.m_login";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_date", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["20"]["m_sql"] = "add_date";
protoArray["20"]["m_srcTableName"] = "dbo.m_login";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_user", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["22"]["m_sql"] = "edit_user";
protoArray["22"]["m_srcTableName"] = "dbo.m_login";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_date", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["24"]["m_sql"] = "edit_date";
protoArray["24"]["m_srcTableName"] = "dbo.m_login";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "userpic", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["26"]["m_sql"] = "userpic";
protoArray["26"]["m_srcTableName"] = "dbo.m_login";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ext_security_id", "m_strTable", "dbo.m_login", "m_srcTableName", "dbo.m_login"));

protoArray["28"]["m_sql"] = "ext_security_id";
protoArray["28"]["m_srcTableName"] = "dbo.m_login";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_link"] = "SQLL_MAIN";
protoArray["31"] = SettingsMap.GetArray();
protoArray["31"]["m_strName"] = "dbo.m_login";
protoArray["31"]["m_srcTableName"] = "dbo.m_login";
protoArray["31"]["m_columns"] = SettingsMap.GetArray();
protoArray["31"]["m_columns"].Add("login_id");
protoArray["31"]["m_columns"].Add("username");
protoArray["31"]["m_columns"].Add("password");
protoArray["31"]["m_columns"].Add("fullname");
protoArray["31"]["m_columns"].Add("email");
protoArray["31"]["m_columns"].Add("isactive");
protoArray["31"]["m_columns"].Add("add_user");
protoArray["31"]["m_columns"].Add("add_date");
protoArray["31"]["m_columns"].Add("edit_user");
protoArray["31"]["m_columns"].Add("edit_date");
protoArray["31"]["m_columns"].Add("userpic");
protoArray["31"]["m_columns"].Add("ext_security_id");
obj = new SQLTable(protoArray["31"]);

protoArray["30"]["m_table"] = obj;
protoArray["30"]["m_sql"] = "dbo.m_login";
protoArray["30"]["m_alias"] = "";
protoArray["30"]["m_srcTableName"] = "dbo.m_login";
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_sql"] = "";
protoArray["32"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["32"]["m_column"] = obj;
protoArray["32"]["m_contained"] = SettingsMap.GetArray();
protoArray["32"]["m_strCase"] = "";
protoArray["32"]["m_havingmode"] = false;
protoArray["32"]["m_inBrackets"] = false;
protoArray["32"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["32"]);

protoArray["30"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["30"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.m_login";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["m_login"] = obj;

				
		
			tdataArray["m_login"][".sqlquery"] = queryData_Array["m_login"];
			tdataArray["m_login"][".hasEvents"] = false;
			GlobalVars.tables_data["m_login"] = tdataArray["m_login"];
		}
	}

}
