using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public partial class CommonFunctions
	{
		public static XVar getMenuNodes_main(dynamic _param_menuNodesObject)
		{
			#region pass-by-value parameters
			dynamic menuNodesObject = XVar.Clone(_param_menuNodesObject);
			#endregion

			dynamic menuNode = XVar.Array();
			menuNodesObject.menuNodes.InitAndSetArrayItem(XVar.Array(), "main");
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("1", "id");
			menuNode.InitAndSetArrayItem("Dashboard", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("v1", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("Dashboard")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("fa-dashboard", "icon");
			menuNode.InitAndSetArrayItem("3", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Dashboard", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("2", "id");
			menuNode.InitAndSetArrayItem("configuration", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("fa-gears", "icon");
			menuNode.InitAndSetArrayItem("3", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("configuration", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("3", "id");
			menuNode.InitAndSetArrayItem("Login", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_login", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("2", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Login", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("4", "id");
			menuNode.InitAndSetArrayItem("Location", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_location_office", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("2", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Location", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("5", "id");
			menuNode.InitAndSetArrayItem("Mapping Location", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_mapping_location", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("2", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Mapping Location", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("6", "id");
			menuNode.InitAndSetArrayItem("Employee", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_employee", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("2", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Employee", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("7", "id");
			menuNode.InitAndSetArrayItem("Meeting Room", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_meeting_room", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("2", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Meeting Room", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("8", "id");
			menuNode.InitAndSetArrayItem("General Affair (GA)", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("fa-shopping-cart", "icon");
			menuNode.InitAndSetArrayItem("3", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("General Affair (GA)", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("9", "id");
			menuNode.InitAndSetArrayItem("Incoming Document Registration", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.t_register_doc", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("8", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Incoming Document Registration", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("10", "id");
			menuNode.InitAndSetArrayItem("Stamp Duty", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.m_login", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("8", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Stamp Duty", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("11", "id");
			menuNode.InitAndSetArrayItem("Visitor Registration", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.t_visitor_log", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("8", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Visitor Registration", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			return null;
		}
	}
}
