<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'LOGIN' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => '09u6WiXH4thjvir3G0f9',
'JWTSecret' => 'UBAujtpJmGveCT6G0Bgc',
'forceExpire' => true,
'keepAlive' => false ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'changePasswordPage' => true,
'changePwdPage' => false,
'registerPage' => false,
'remindPage' => false,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'LOG_audit' ),
'lockingTable' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => '˂Create new˃' ),
'tables' => array( 'BSM' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'LOGIN' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'WEB_BTN02',
'loginDataSource' => 'LOGIN',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'LOG_',
'dpTableConnId' => 'u736239518_btn_at_154_41_241_2',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'LOGIN' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>