using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_t_register_doc
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["t_register_doc"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".ShortName"] = "t_register_doc";
			tdataArray["t_register_doc"][".OwnerID"] = "";
			tdataArray["t_register_doc"][".OriginalTable"] = "dbo.t_register_doc";
			tdataArray["t_register_doc"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["t_register_doc"][".originalPagesByType"] = tdataArray["t_register_doc"][".pagesByType"];
			tdataArray["t_register_doc"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["t_register_doc"][".originalPages"] = tdataArray["t_register_doc"][".pages"];
			tdataArray["t_register_doc"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["t_register_doc"][".originalDefaultPages"] = tdataArray["t_register_doc"][".defaultPages"];
			fieldLabelsArray["t_register_doc"] = SettingsMap.GetArray();
			fieldToolTipsArray["t_register_doc"] = SettingsMap.GetArray();
			pageTitlesArray["t_register_doc"] = SettingsMap.GetArray();
			placeHoldersArray["t_register_doc"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["t_register_doc"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["t_register_doc"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["t_register_doc"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["t_register_doc"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["t_register_doc"]["English"]["t_register_doc_id"] = "T Register Doc Id";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_doc_id"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_doc_id"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_doc_no"] = "Registration No";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_doc_no"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_doc_no"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_date"] = "Date";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_date"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_date"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_location_id"] = "Location";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_location_id"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_location_id"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_doc_owner"] = "Owner";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_doc_owner"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_doc_owner"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_images"] = "Images";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_images"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_images"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_note"] = "Note";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_note"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_note"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["t_register_status"] = "Status";
				fieldToolTipsArray["t_register_doc"]["English"]["t_register_status"] = "";
				placeHoldersArray["t_register_doc"]["English"]["t_register_status"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["add_user"] = "Add User";
				fieldToolTipsArray["t_register_doc"]["English"]["add_user"] = "";
				placeHoldersArray["t_register_doc"]["English"]["add_user"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["add_date"] = "Add Date";
				fieldToolTipsArray["t_register_doc"]["English"]["add_date"] = "";
				placeHoldersArray["t_register_doc"]["English"]["add_date"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["edit_user"] = "Edit User";
				fieldToolTipsArray["t_register_doc"]["English"]["edit_user"] = "";
				placeHoldersArray["t_register_doc"]["English"]["edit_user"] = "";
				fieldLabelsArray["t_register_doc"]["English"]["edit_date"] = "Edit Date";
				fieldToolTipsArray["t_register_doc"]["English"]["edit_date"] = "";
				placeHoldersArray["t_register_doc"]["English"]["edit_date"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["t_register_doc"]["English"])))
				{
					tdataArray["t_register_doc"][".isUseToolTips"] = true;
				}
			}
			tdataArray["t_register_doc"][".NCSearch"] = true;
			tdataArray["t_register_doc"][".scrollGridBody"] = true;
			tdataArray["t_register_doc"][".shortTableName"] = "t_register_doc";
			tdataArray["t_register_doc"][".nSecOptions"] = 0;
			tdataArray["t_register_doc"][".mainTableOwnerID"] = "";
			tdataArray["t_register_doc"][".entityType"] = 0;
			tdataArray["t_register_doc"][".connId"] = "TSUNDB_at_alpha_talisman_co_id";
			tdataArray["t_register_doc"][".strOriginalTableName"] = "dbo.t_register_doc";
			tdataArray["t_register_doc"][".showAddInPopup"] = false;
			tdataArray["t_register_doc"][".showEditInPopup"] = false;
			tdataArray["t_register_doc"][".showViewInPopup"] = false;
			tdataArray["t_register_doc"][".listAjax"] = false;
			tdataArray["t_register_doc"][".audit"] = true;
			tdataArray["t_register_doc"][".locking"] = false;
			GlobalVars.pages = tdataArray["t_register_doc"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["t_register_doc"][".edit"] = true;
				tdataArray["t_register_doc"][".afterEditAction"] = 1;
				tdataArray["t_register_doc"][".closePopupAfterEdit"] = 1;
				tdataArray["t_register_doc"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["t_register_doc"][".add"] = true;
				tdataArray["t_register_doc"][".afterAddAction"] = 1;
				tdataArray["t_register_doc"][".closePopupAfterAdd"] = 1;
				tdataArray["t_register_doc"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["t_register_doc"][".list"] = true;
			}
			tdataArray["t_register_doc"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["t_register_doc"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["t_register_doc"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["t_register_doc"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["t_register_doc"][".printFriendly"] = true;
			}
			tdataArray["t_register_doc"][".showSimpleSearchOptions"] = true;
			tdataArray["t_register_doc"][".allowShowHideFields"] = true;
			tdataArray["t_register_doc"][".allowFieldsReordering"] = true;
			tdataArray["t_register_doc"][".isUseAjaxSuggest"] = true;


			tdataArray["t_register_doc"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["t_register_doc"][".buttonsAdded"] = false;
			tdataArray["t_register_doc"][".addPageEvents"] = true;
			tdataArray["t_register_doc"][".isUseTimeForSearch"] = false;
			tdataArray["t_register_doc"][".badgeColor"] = "E67349";
			tdataArray["t_register_doc"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_doc_id");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_doc_no");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_date");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_location_id");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_doc_owner");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_images");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_note");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("t_register_status");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("add_user");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("add_date");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("edit_user");
			tdataArray["t_register_doc"][".googleLikeFields"].Add("edit_date");
			tdataArray["t_register_doc"][".tableType"] = "list";
			tdataArray["t_register_doc"][".printerPageOrientation"] = 0;
			tdataArray["t_register_doc"][".nPrinterPageScale"] = 100;
			tdataArray["t_register_doc"][".nPrinterSplitRecords"] = 40;
			tdataArray["t_register_doc"][".geocodingEnabled"] = false;
			tdataArray["t_register_doc"][".isDisplayLoading"] = true;
			tdataArray["t_register_doc"][".pageSize"] = 20;
			tdataArray["t_register_doc"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["t_register_doc"][".strOrderBy"] = tstrOrderBy;
			tdataArray["t_register_doc"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["t_register_doc"][".sqlHead"] = "SELECT t_register_doc_id,  t_register_doc_no,  t_register_date,  t_register_location_id,  t_register_doc_owner,  t_register_images,  t_register_note,  t_register_status,  add_user,  CONVERT(varchar, add_date, 22) AS add_date,  edit_user,  edit_date";
			tdataArray["t_register_doc"][".sqlFrom"] = "FROM dbo.t_register_doc";
			tdataArray["t_register_doc"][".sqlWhereExpr"] = "(t_register_location_id in (select m_location_id from m_mapping_location where username=':user.username'))";
			tdataArray["t_register_doc"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["t_register_doc"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["t_register_doc"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["t_register_doc"][".highlightSearchResults"] = true;
			tableKeysArray["t_register_doc"] = SettingsMap.GetArray();
			tableKeysArray["t_register_doc"].Add("t_register_doc_id");
			tdataArray["t_register_doc"][".Keys"] = tableKeysArray["t_register_doc"];
			tdataArray["t_register_doc"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "t_register_doc_id";
			fdata["GoodName"] = "t_register_doc_id";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_doc_id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "t_register_doc_id";
			fdata["sourceSingle"] = "t_register_doc_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_doc_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_doc_id"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_doc_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "t_register_doc_no";
			fdata["GoodName"] = "t_register_doc_no";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_doc_no");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_doc_no";
			fdata["sourceSingle"] = "t_register_doc_no";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_doc_no";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("DenyDuplicated");
			edata["validateAs"]["customMessages"]["DenyDuplicated"] = new XVar("message", "Value %value% already exists", "messageType", "Text");
			edata["denyDuplicates"] = true;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_doc_no"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_doc_no");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "t_register_date";
			fdata["GoodName"] = "t_register_date";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "t_register_date";
			fdata["sourceSingle"] = "t_register_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 2;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_date"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "t_register_location_id";
			fdata["GoodName"] = "t_register_location_id";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_location_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_location_id";
			fdata["sourceSingle"] = "t_register_location_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_location_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.m_location_office1";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "m_location_id";
			edata["LinkFieldType"] = 3;
			edata["DisplayField"] = "m_location_name";
			edata["LookupOrderBy"] = "";
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_location_id"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_location_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "t_register_doc_owner";
			fdata["GoodName"] = "t_register_doc_owner";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_doc_owner");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_doc_owner";
			fdata["sourceSingle"] = "t_register_doc_owner";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_doc_owner";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.m_employee1";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 2;
			edata["LinkField"] = "m_employee_id";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "NAMA";
			edata["LookupOrderBy"] = "m_employee_id";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_doc_owner"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_doc_owner");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "t_register_images";
			fdata["GoodName"] = "t_register_images";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_images");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_images";
			fdata["sourceSingle"] = "t_register_images";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_images";
			fdata["DeleteAssociatedFile"] = true;
			fdata["CompatibilityMode"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "File-based Image");
			vdata["ShowThumbnail"] = true;
			vdata["ThumbWidth"] = 200;
			vdata["ThumbHeight"] = 150;
			vdata["ImageWidth"] = 300;
			vdata["ImageHeight"] = 100;
			vdata["multipleImgMode"] = 1;
			vdata["maxImages"] = 0;
			vdata["showGallery"] = true;
			vdata["galleryMode"] = 2;
			vdata["captionMode"] = 3;
			vdata["captionField"] = "add_date";
			vdata["imageBorder"] = 1;
			vdata["imageFullWidth"] = 1;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Document upload");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 300;
			edata["ResizeImage"] = true;
			edata["NewSize"] = 300;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_images"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_images");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "t_register_note";
			fdata["GoodName"] = "t_register_note";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_note");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_note";
			fdata["sourceSingle"] = "t_register_note";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_note";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_note"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_note");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "t_register_status";
			fdata["GoodName"] = "t_register_status";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","t_register_status");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_status";
			fdata["sourceSingle"] = "t_register_status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_register_status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["t_register_status"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("t_register_status");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "add_user";
			fdata["GoodName"] = "add_user";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","add_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "add_user";
			fdata["sourceSingle"] = "add_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["add_user"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("add_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "add_date";
			fdata["GoodName"] = "add_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","add_date");
			fdata["FieldType"] = 200;
			fdata["strField"] = "add_date";
			fdata["sourceSingle"] = "add_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "CONVERT(varchar, add_date, 22)";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=23");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["add_date"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("add_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "edit_user";
			fdata["GoodName"] = "edit_user";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","edit_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "edit_user";
			fdata["sourceSingle"] = "edit_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["edit_user"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("edit_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "edit_date";
			fdata["GoodName"] = "edit_date";
			fdata["ownerTable"] = "dbo.t_register_doc";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_register_doc","edit_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "edit_date";
			fdata["sourceSingle"] = "edit_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_register_doc"]["edit_date"] = fdata;
			tdataArray["t_register_doc"][".searchableFields"].Add("edit_date");
			GlobalVars.tables_data["dbo.t_register_doc"] = tdataArray["t_register_doc"];
			GlobalVars.field_labels["dbo_t_register_doc"] = fieldLabelsArray["t_register_doc"];
			GlobalVars.fieldToolTips["dbo_t_register_doc"] = fieldToolTipsArray["t_register_doc"];
			GlobalVars.placeHolders["dbo_t_register_doc"] = placeHoldersArray["t_register_doc"];
			GlobalVars.page_titles["dbo_t_register_doc"] = pageTitlesArray["t_register_doc"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.t_register_doc"));
			GlobalVars.detailsTablesData["dbo.t_register_doc"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.t_register_doc"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "t_register_doc_id,  t_register_doc_no,  t_register_date,  t_register_location_id,  t_register_doc_owner,  t_register_images,  t_register_note,  t_register_status,  add_user,  CONVERT(varchar, add_date, 22) AS add_date,  edit_user,  edit_date";
protoArray["0"]["m_strFrom"] = "FROM dbo.t_register_doc";
protoArray["0"]["m_strWhere"] = "(t_register_location_id in (select m_location_id from m_mapping_location where username=':user.username'))";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "t_register_location_id in (select m_location_id from m_mapping_location where username=':user.username')";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLField(new XVar("m_strName", "t_register_location_id", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "in (select m_location_id from m_mapping_location where username=':user.username')";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_doc_id", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["6"]["m_sql"] = "t_register_doc_id";
protoArray["6"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_doc_no", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["8"]["m_sql"] = "t_register_doc_no";
protoArray["8"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_date", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["10"]["m_sql"] = "t_register_date";
protoArray["10"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_location_id", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["12"]["m_sql"] = "t_register_location_id";
protoArray["12"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_doc_owner", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["14"]["m_sql"] = "t_register_doc_owner";
protoArray["14"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_images", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["16"]["m_sql"] = "t_register_images";
protoArray["16"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_note", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["18"]["m_sql"] = "t_register_note";
protoArray["18"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_register_status", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["20"]["m_sql"] = "t_register_status";
protoArray["20"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_user", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["22"]["m_sql"] = "add_user";
protoArray["22"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
protoArray["25"] = SettingsMap.GetArray();
protoArray["25"]["m_functiontype"] = "SQLF_CUSTOM";
protoArray["25"]["m_arguments"] = SettingsMap.GetArray();
obj = new SQLNonParsed(new XVar("m_sql", "varchar"));

protoArray["25"]["m_arguments"].Add(obj);
obj = new SQLNonParsed(new XVar("m_sql", "add_date"));

protoArray["25"]["m_arguments"].Add(obj);
obj = new SQLNonParsed(new XVar("m_sql", "22"));

protoArray["25"]["m_arguments"].Add(obj);
protoArray["25"]["m_strFunctionName"] = "CONVERT";
obj = new SQLFunctionCall(protoArray["25"]);

protoArray["24"]["m_sql"] = "CONVERT(varchar, add_date, 22)";
protoArray["24"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "add_date";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["29"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_user", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["29"]["m_sql"] = "edit_user";
protoArray["29"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["29"]["m_expr"] = obj;
protoArray["29"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["29"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["31"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_date", "m_strTable", "dbo.t_register_doc", "m_srcTableName", "dbo.t_register_doc"));

protoArray["31"]["m_sql"] = "edit_date";
protoArray["31"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["31"]["m_expr"] = obj;
protoArray["31"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["31"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["33"] = SettingsMap.GetArray();
protoArray["33"]["m_link"] = "SQLL_MAIN";
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_strName"] = "dbo.t_register_doc";
protoArray["34"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["34"]["m_columns"] = SettingsMap.GetArray();
protoArray["34"]["m_columns"].Add("t_register_doc_id");
protoArray["34"]["m_columns"].Add("t_register_doc_no");
protoArray["34"]["m_columns"].Add("t_register_date");
protoArray["34"]["m_columns"].Add("t_register_location_id");
protoArray["34"]["m_columns"].Add("t_register_doc_owner");
protoArray["34"]["m_columns"].Add("t_register_images");
protoArray["34"]["m_columns"].Add("t_register_note");
protoArray["34"]["m_columns"].Add("t_register_status");
protoArray["34"]["m_columns"].Add("add_user");
protoArray["34"]["m_columns"].Add("add_date");
protoArray["34"]["m_columns"].Add("edit_user");
protoArray["34"]["m_columns"].Add("edit_date");
obj = new SQLTable(protoArray["34"]);

protoArray["33"]["m_table"] = obj;
protoArray["33"]["m_sql"] = "dbo.t_register_doc";
protoArray["33"]["m_alias"] = "";
protoArray["33"]["m_srcTableName"] = "dbo.t_register_doc";
protoArray["35"] = SettingsMap.GetArray();
protoArray["35"]["m_sql"] = "";
protoArray["35"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["35"]["m_column"] = obj;
protoArray["35"]["m_contained"] = SettingsMap.GetArray();
protoArray["35"]["m_strCase"] = "";
protoArray["35"]["m_havingmode"] = false;
protoArray["35"]["m_inBrackets"] = false;
protoArray["35"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["35"]);

protoArray["33"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["33"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.t_register_doc";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["t_register_doc"] = obj;

				
		
			tdataArray["t_register_doc"][".sqlquery"] = queryData_Array["t_register_doc"];
			tdataArray["t_register_doc"][".hasEvents"] = true;
			GlobalVars.tables_data["t_register_doc"] = tdataArray["t_register_doc"];
		}
	}

}
