using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_t_visitor_log
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["t_visitor_log"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".ShortName"] = "t_visitor_log";
			tdataArray["t_visitor_log"][".OwnerID"] = "";
			tdataArray["t_visitor_log"][".OriginalTable"] = "dbo.t_visitor_log";
			tdataArray["t_visitor_log"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["t_visitor_log"][".originalPagesByType"] = tdataArray["t_visitor_log"][".pagesByType"];
			tdataArray["t_visitor_log"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["t_visitor_log"][".originalPages"] = tdataArray["t_visitor_log"][".pages"];
			tdataArray["t_visitor_log"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["t_visitor_log"][".originalDefaultPages"] = tdataArray["t_visitor_log"][".defaultPages"];
			fieldLabelsArray["t_visitor_log"] = SettingsMap.GetArray();
			fieldToolTipsArray["t_visitor_log"] = SettingsMap.GetArray();
			pageTitlesArray["t_visitor_log"] = SettingsMap.GetArray();
			placeHoldersArray["t_visitor_log"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["t_visitor_log"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["t_visitor_log"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["t_visitor_log"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["t_visitor_log"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_id"] = "T Visitor Log Id";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_id"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_id"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_name"] = "Name";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_name"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_name"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_company"] = "Company";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_company"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_company"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_time_in"] = "Time In";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_time_in"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_time_in"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_time_out"] = "Time Out";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_time_out"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_time_out"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_images"] = "Images";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_images"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_images"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_owner"] = "Owner";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_owner"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_owner"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_room_id"] = "Meeting Room";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_room_id"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_room_id"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["add_user"] = "Add User";
				fieldToolTipsArray["t_visitor_log"]["English"]["add_user"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["add_user"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["add_date"] = "Add Date";
				fieldToolTipsArray["t_visitor_log"]["English"]["add_date"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["add_date"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["edit_user"] = "Edit User";
				fieldToolTipsArray["t_visitor_log"]["English"]["edit_user"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["edit_user"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["edit_date"] = "Edit Date";
				fieldToolTipsArray["t_visitor_log"]["English"]["edit_date"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["edit_date"] = "";
				fieldLabelsArray["t_visitor_log"]["English"]["t_visitor_log_location_id"] = "Location";
				fieldToolTipsArray["t_visitor_log"]["English"]["t_visitor_log_location_id"] = "";
				placeHoldersArray["t_visitor_log"]["English"]["t_visitor_log_location_id"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["t_visitor_log"]["English"])))
				{
					tdataArray["t_visitor_log"][".isUseToolTips"] = true;
				}
			}
			tdataArray["t_visitor_log"][".NCSearch"] = true;
			tdataArray["t_visitor_log"][".scrollGridBody"] = true;
			tdataArray["t_visitor_log"][".shortTableName"] = "t_visitor_log";
			tdataArray["t_visitor_log"][".nSecOptions"] = 0;
			tdataArray["t_visitor_log"][".mainTableOwnerID"] = "";
			tdataArray["t_visitor_log"][".entityType"] = 0;
			tdataArray["t_visitor_log"][".connId"] = "TSUNDB_at_alpha_talisman_co_id";
			tdataArray["t_visitor_log"][".strOriginalTableName"] = "dbo.t_visitor_log";
			tdataArray["t_visitor_log"][".showAddInPopup"] = false;
			tdataArray["t_visitor_log"][".showEditInPopup"] = false;
			tdataArray["t_visitor_log"][".showViewInPopup"] = false;
			tdataArray["t_visitor_log"][".listAjax"] = false;
			tdataArray["t_visitor_log"][".audit"] = false;
			tdataArray["t_visitor_log"][".locking"] = false;
			GlobalVars.pages = tdataArray["t_visitor_log"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["t_visitor_log"][".edit"] = true;
				tdataArray["t_visitor_log"][".afterEditAction"] = 1;
				tdataArray["t_visitor_log"][".closePopupAfterEdit"] = 1;
				tdataArray["t_visitor_log"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["t_visitor_log"][".add"] = true;
				tdataArray["t_visitor_log"][".afterAddAction"] = 1;
				tdataArray["t_visitor_log"][".closePopupAfterAdd"] = 1;
				tdataArray["t_visitor_log"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["t_visitor_log"][".list"] = true;
			}
			tdataArray["t_visitor_log"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["t_visitor_log"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["t_visitor_log"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["t_visitor_log"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["t_visitor_log"][".printFriendly"] = true;
			}
			tdataArray["t_visitor_log"][".showSimpleSearchOptions"] = true;
			tdataArray["t_visitor_log"][".allowShowHideFields"] = true;
			tdataArray["t_visitor_log"][".allowFieldsReordering"] = true;
			tdataArray["t_visitor_log"][".isUseAjaxSuggest"] = true;


			tdataArray["t_visitor_log"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["t_visitor_log"][".buttonsAdded"] = false;
			tdataArray["t_visitor_log"][".addPageEvents"] = false;
			tdataArray["t_visitor_log"][".isUseTimeForSearch"] = true;
			tdataArray["t_visitor_log"][".badgeColor"] = "1E90FF";
			tdataArray["t_visitor_log"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_id");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_name");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_company");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_location_id");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_time_in");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_time_out");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_images");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_owner");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("t_visitor_log_room_id");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("add_user");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("add_date");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("edit_user");
			tdataArray["t_visitor_log"][".googleLikeFields"].Add("edit_date");
			tdataArray["t_visitor_log"][".tableType"] = "list";
			tdataArray["t_visitor_log"][".printerPageOrientation"] = 0;
			tdataArray["t_visitor_log"][".nPrinterPageScale"] = 100;
			tdataArray["t_visitor_log"][".nPrinterSplitRecords"] = 40;
			tdataArray["t_visitor_log"][".geocodingEnabled"] = false;
			tdataArray["t_visitor_log"][".isDisplayLoading"] = true;
			tdataArray["t_visitor_log"][".pageSize"] = 20;
			tdataArray["t_visitor_log"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["t_visitor_log"][".strOrderBy"] = tstrOrderBy;
			tdataArray["t_visitor_log"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["t_visitor_log"][".sqlHead"] = "SELECT t_visitor_log_id,  	t_visitor_log_name,  	t_visitor_log_company,  	t_visitor_log_location_id,  	t_visitor_log_time_in,  	t_visitor_log_time_out,  	t_visitor_log_images,  	t_visitor_log_owner,  	t_visitor_log_room_id,  	add_user,  	add_date,  	edit_user,  	edit_date";
			tdataArray["t_visitor_log"][".sqlFrom"] = "FROM dbo.t_visitor_log";
			tdataArray["t_visitor_log"][".sqlWhereExpr"] = "(t_visitor_log_location_id in (select m_location_id from m_mapping_location where username=':user.username'))";
			tdataArray["t_visitor_log"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["t_visitor_log"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["t_visitor_log"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["t_visitor_log"][".highlightSearchResults"] = true;
			tableKeysArray["t_visitor_log"] = SettingsMap.GetArray();
			tableKeysArray["t_visitor_log"].Add("t_visitor_log_id");
			tdataArray["t_visitor_log"][".Keys"] = tableKeysArray["t_visitor_log"];
			tdataArray["t_visitor_log"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "t_visitor_log_id";
			fdata["GoodName"] = "t_visitor_log_id";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "t_visitor_log_id";
			fdata["sourceSingle"] = "t_visitor_log_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_id"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "t_visitor_log_name";
			fdata["GoodName"] = "t_visitor_log_name";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_visitor_log_name";
			fdata["sourceSingle"] = "t_visitor_log_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_name"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "t_visitor_log_company";
			fdata["GoodName"] = "t_visitor_log_company";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_company");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_visitor_log_company";
			fdata["sourceSingle"] = "t_visitor_log_company";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_company";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_company"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_company");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "t_visitor_log_location_id";
			fdata["GoodName"] = "t_visitor_log_location_id";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_location_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_visitor_log_location_id";
			fdata["sourceSingle"] = "t_visitor_log_location_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_location_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.m_location_office1";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "m_location_id";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "m_location_name";
			edata["LookupOrderBy"] = "m_location_id";
			edata["DependentLookups"] = SettingsMap.GetArray();
			edata["DependentLookups"].Add("t_visitor_log_room_id");
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_location_id"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_location_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "t_visitor_log_time_in";
			fdata["GoodName"] = "t_visitor_log_time_in";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_time_in");
			fdata["FieldType"] = 135;
			fdata["strField"] = "t_visitor_log_time_in";
			fdata["sourceSingle"] = "t_visitor_log_time_in";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_time_in";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Time");
			vdata["timeFormatData"] = new XVar("showSeconds", false, "showDaysInTotals", false, "timeFormat", 0);
			vdata["timeFormatData"]["showSeconds"] = true;
			vdata["timeFormatData"]["showDaysInTotals"] = true;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Time");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			hours = 24;
			edata["FormatTimeAttrs"] = new XVar("useTimePicker", 1, "hours", hours, "minutes", 1, "showSeconds", 0);
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_time_in"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_time_in");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "t_visitor_log_time_out";
			fdata["GoodName"] = "t_visitor_log_time_out";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_time_out");
			fdata["FieldType"] = 135;
			fdata["strField"] = "t_visitor_log_time_out";
			fdata["sourceSingle"] = "t_visitor_log_time_out";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_time_out";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Time");
			vdata["timeFormatData"] = new XVar("showSeconds", false, "showDaysInTotals", false, "timeFormat", 0);
			vdata["timeFormatData"]["showSeconds"] = true;
			vdata["timeFormatData"]["showDaysInTotals"] = true;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Time");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			hours = 24;
			edata["FormatTimeAttrs"] = new XVar("useTimePicker", 1, "hours", hours, "minutes", 1, "showSeconds", 0);
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_time_out"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_time_out");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "t_visitor_log_images";
			fdata["GoodName"] = "t_visitor_log_images";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_images");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_visitor_log_images";
			fdata["sourceSingle"] = "t_visitor_log_images";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_images";
			fdata["DeleteAssociatedFile"] = true;
			fdata["CompatibilityMode"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "File-based Image");
			vdata["ShowThumbnail"] = true;
			vdata["ThumbWidth"] = 200;
			vdata["ThumbHeight"] = 150;
			vdata["ImageWidth"] = 60;
			vdata["ImageHeight"] = 40;
			vdata["multipleImgMode"] = 1;
			vdata["maxImages"] = 0;
			vdata["showGallery"] = true;
			vdata["galleryMode"] = 2;
			vdata["captionMode"] = 2;
			vdata["captionField"] = "";
			vdata["imageBorder"] = 1;
			vdata["imageFullWidth"] = 1;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Document upload");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_images"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_images");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "t_visitor_log_owner";
			fdata["GoodName"] = "t_visitor_log_owner";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_owner");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_visitor_log_owner";
			fdata["sourceSingle"] = "t_visitor_log_owner";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_owner";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.m_employee1";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 2;
			edata["LinkField"] = "m_employee_id";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "NAMA";
			edata["LookupOrderBy"] = "m_employee_id";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_owner"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_owner");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "t_visitor_log_room_id";
			fdata["GoodName"] = "t_visitor_log_room_id";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","t_visitor_log_room_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_visitor_log_room_id";
			fdata["sourceSingle"] = "t_visitor_log_room_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "t_visitor_log_room_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.m_meeting_room";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "m_meeting_room_id";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "m_meeting_room_name";
			edata["LookupOrderBy"] = "m_meeting_room_id";
			edata["UseCategory"] = true;
			edata["categoryFields"] = SettingsMap.GetArray();
			edata["categoryFields"].Add(new XVar("main", "t_visitor_log_location_id", "lookup", "m_meeting_room_location_id"));
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["t_visitor_log_room_id"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("t_visitor_log_room_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "add_user";
			fdata["GoodName"] = "add_user";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","add_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "add_user";
			fdata["sourceSingle"] = "add_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["add_user"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("add_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "add_date";
			fdata["GoodName"] = "add_date";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","add_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "add_date";
			fdata["sourceSingle"] = "add_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "add_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["add_date"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("add_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "edit_user";
			fdata["GoodName"] = "edit_user";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","edit_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "edit_user";
			fdata["sourceSingle"] = "edit_user";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["edit_user"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("edit_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "edit_date";
			fdata["GoodName"] = "edit_date";
			fdata["ownerTable"] = "dbo.t_visitor_log";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_t_visitor_log","edit_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "edit_date";
			fdata["sourceSingle"] = "edit_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "edit_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["t_visitor_log"]["edit_date"] = fdata;
			tdataArray["t_visitor_log"][".searchableFields"].Add("edit_date");
			GlobalVars.tables_data["dbo.t_visitor_log"] = tdataArray["t_visitor_log"];
			GlobalVars.field_labels["dbo_t_visitor_log"] = fieldLabelsArray["t_visitor_log"];
			GlobalVars.fieldToolTips["dbo_t_visitor_log"] = fieldToolTipsArray["t_visitor_log"];
			GlobalVars.placeHolders["dbo_t_visitor_log"] = placeHoldersArray["t_visitor_log"];
			GlobalVars.page_titles["dbo_t_visitor_log"] = pageTitlesArray["t_visitor_log"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.t_visitor_log"));
			GlobalVars.detailsTablesData["dbo.t_visitor_log"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.t_visitor_log"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "t_visitor_log_id,  	t_visitor_log_name,  	t_visitor_log_company,  	t_visitor_log_location_id,  	t_visitor_log_time_in,  	t_visitor_log_time_out,  	t_visitor_log_images,  	t_visitor_log_owner,  	t_visitor_log_room_id,  	add_user,  	add_date,  	edit_user,  	edit_date";
protoArray["0"]["m_strFrom"] = "FROM dbo.t_visitor_log";
protoArray["0"]["m_strWhere"] = "(t_visitor_log_location_id in (select m_location_id from m_mapping_location where username=':user.username'))";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "t_visitor_log_location_id in (select m_location_id from m_mapping_location where username=':user.username')";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLField(new XVar("m_strName", "t_visitor_log_location_id", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "in (select m_location_id from m_mapping_location where username=':user.username')";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_id", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["6"]["m_sql"] = "t_visitor_log_id";
protoArray["6"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_name", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["8"]["m_sql"] = "t_visitor_log_name";
protoArray["8"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_company", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["10"]["m_sql"] = "t_visitor_log_company";
protoArray["10"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_location_id", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["12"]["m_sql"] = "t_visitor_log_location_id";
protoArray["12"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_time_in", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["14"]["m_sql"] = "t_visitor_log_time_in";
protoArray["14"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_time_out", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["16"]["m_sql"] = "t_visitor_log_time_out";
protoArray["16"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_images", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["18"]["m_sql"] = "t_visitor_log_images";
protoArray["18"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_owner", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["20"]["m_sql"] = "t_visitor_log_owner";
protoArray["20"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "t_visitor_log_room_id", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["22"]["m_sql"] = "t_visitor_log_room_id";
protoArray["22"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_user", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["24"]["m_sql"] = "add_user";
protoArray["24"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "add_date", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["26"]["m_sql"] = "add_date";
protoArray["26"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_user", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["28"]["m_sql"] = "edit_user";
protoArray["28"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "edit_date", "m_strTable", "dbo.t_visitor_log", "m_srcTableName", "dbo.t_visitor_log"));

protoArray["30"]["m_sql"] = "edit_date";
protoArray["30"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_link"] = "SQLL_MAIN";
protoArray["33"] = SettingsMap.GetArray();
protoArray["33"]["m_strName"] = "dbo.t_visitor_log";
protoArray["33"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["33"]["m_columns"] = SettingsMap.GetArray();
protoArray["33"]["m_columns"].Add("t_visitor_log_id");
protoArray["33"]["m_columns"].Add("t_visitor_log_name");
protoArray["33"]["m_columns"].Add("t_visitor_log_company");
protoArray["33"]["m_columns"].Add("t_visitor_log_location_id");
protoArray["33"]["m_columns"].Add("t_visitor_log_time_in");
protoArray["33"]["m_columns"].Add("t_visitor_log_time_out");
protoArray["33"]["m_columns"].Add("t_visitor_log_images");
protoArray["33"]["m_columns"].Add("t_visitor_log_owner");
protoArray["33"]["m_columns"].Add("t_visitor_log_room_id");
protoArray["33"]["m_columns"].Add("add_user");
protoArray["33"]["m_columns"].Add("add_date");
protoArray["33"]["m_columns"].Add("edit_user");
protoArray["33"]["m_columns"].Add("edit_date");
obj = new SQLTable(protoArray["33"]);

protoArray["32"]["m_table"] = obj;
protoArray["32"]["m_sql"] = "dbo.t_visitor_log";
protoArray["32"]["m_alias"] = "";
protoArray["32"]["m_srcTableName"] = "dbo.t_visitor_log";
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_sql"] = "";
protoArray["34"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["34"]["m_column"] = obj;
protoArray["34"]["m_contained"] = SettingsMap.GetArray();
protoArray["34"]["m_strCase"] = "";
protoArray["34"]["m_havingmode"] = false;
protoArray["34"]["m_inBrackets"] = false;
protoArray["34"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["34"]);

protoArray["32"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["32"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.t_visitor_log";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["t_visitor_log"] = obj;

				
		
			tdataArray["t_visitor_log"][".sqlquery"] = queryData_Array["t_visitor_log"];
			tdataArray["t_visitor_log"][".hasEvents"] = false;
			GlobalVars.tables_data["t_visitor_log"] = tdataArray["t_visitor_log"];
		}
	}

}
