<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v1  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v1_snippet( &$header, &$icon )
	{
		echo "<div class='row'>
  <!-- View sales -->
  <div class='col-xl-4 mb-4 col-lg-5 col-12'>
    <div class='card'>
<div class='d-flex align-items-end row'>
        <div class='col-7'>
          <div class='card-body text-nowrap'>
            <h5 class='card-title mb-0'>Congratulations John! 🎉</h5>
            <p class='mb-2'>Best seller of the month</p>
            <h4 class='text-primary mb-1'>$48.9k</h4>
            <a href='javascript:' class='btn btn-primary waves-effect waves-light'>View Sales</a>
          </div>


</div>
</div>
</div>";
	}

}
?>