using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_vt_register_doc
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["vt_register_doc"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".ShortName"] = "vt_register_doc";
			tdataArray["vt_register_doc"][".OwnerID"] = "";
			tdataArray["vt_register_doc"][".OriginalTable"] = "vt_register_doc";
			tdataArray["vt_register_doc"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["vt_register_doc"][".originalPagesByType"] = tdataArray["vt_register_doc"][".pagesByType"];
			tdataArray["vt_register_doc"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["vt_register_doc"][".originalPages"] = tdataArray["vt_register_doc"][".pages"];
			tdataArray["vt_register_doc"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["vt_register_doc"][".originalDefaultPages"] = tdataArray["vt_register_doc"][".defaultPages"];
			fieldLabelsArray["vt_register_doc"] = SettingsMap.GetArray();
			fieldToolTipsArray["vt_register_doc"] = SettingsMap.GetArray();
			pageTitlesArray["vt_register_doc"] = SettingsMap.GetArray();
			placeHoldersArray["vt_register_doc"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["vt_register_doc"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["vt_register_doc"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["vt_register_doc"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["vt_register_doc"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_doc_id"] = "Register Id";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_doc_id"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_doc_id"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_doc_no"] = "Register No";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_doc_no"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_doc_no"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_date"] = "Date";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_date"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_date"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_location_id"] = "Location";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_location_id"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_location_id"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_doc_owner"] = "Owner";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_doc_owner"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_doc_owner"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_status"] = "Status";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_status"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_status"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_images"] = "Images";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_images"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_images"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["t_register_note"] = "Note";
				fieldToolTipsArray["vt_register_doc"]["English"]["t_register_note"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["t_register_note"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["add_user"] = "Add User";
				fieldToolTipsArray["vt_register_doc"]["English"]["add_user"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["add_user"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["add_date"] = "Add Date";
				fieldToolTipsArray["vt_register_doc"]["English"]["add_date"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["add_date"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["edit_user"] = "Edit User";
				fieldToolTipsArray["vt_register_doc"]["English"]["edit_user"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["edit_user"] = "";
				fieldLabelsArray["vt_register_doc"]["English"]["edit_date"] = "Edit Date";
				fieldToolTipsArray["vt_register_doc"]["English"]["edit_date"] = "";
				placeHoldersArray["vt_register_doc"]["English"]["edit_date"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["vt_register_doc"]["English"])))
				{
					tdataArray["vt_register_doc"][".isUseToolTips"] = true;
				}
			}
			tdataArray["vt_register_doc"][".NCSearch"] = true;
			tdataArray["vt_register_doc"][".shortTableName"] = "vt_register_doc";
			tdataArray["vt_register_doc"][".nSecOptions"] = 0;
			tdataArray["vt_register_doc"][".mainTableOwnerID"] = "";
			tdataArray["vt_register_doc"][".entityType"] = 6;
			tdataArray["vt_register_doc"][".connId"] = "TSUNDB_at_alpha_talisman_co_id";
			tdataArray["vt_register_doc"][".strOriginalTableName"] = "vt_register_doc";
			tdataArray["vt_register_doc"][".showAddInPopup"] = false;
			tdataArray["vt_register_doc"][".showEditInPopup"] = false;
			tdataArray["vt_register_doc"][".showViewInPopup"] = false;
			tdataArray["vt_register_doc"][".listAjax"] = false;
			tdataArray["vt_register_doc"][".audit"] = true;
			tdataArray["vt_register_doc"][".locking"] = false;
			GlobalVars.pages = tdataArray["vt_register_doc"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["vt_register_doc"][".edit"] = true;
				tdataArray["vt_register_doc"][".afterEditAction"] = 1;
				tdataArray["vt_register_doc"][".closePopupAfterEdit"] = 1;
				tdataArray["vt_register_doc"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["vt_register_doc"][".add"] = true;
				tdataArray["vt_register_doc"][".afterAddAction"] = 1;
				tdataArray["vt_register_doc"][".closePopupAfterAdd"] = 1;
				tdataArray["vt_register_doc"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["vt_register_doc"][".list"] = true;
			}
			tdataArray["vt_register_doc"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["vt_register_doc"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["vt_register_doc"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["vt_register_doc"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["vt_register_doc"][".printFriendly"] = true;
			}
			tdataArray["vt_register_doc"][".showSimpleSearchOptions"] = true;
			tdataArray["vt_register_doc"][".allowShowHideFields"] = true;
			tdataArray["vt_register_doc"][".allowFieldsReordering"] = true;
			tdataArray["vt_register_doc"][".isUseAjaxSuggest"] = false;


			tdataArray["vt_register_doc"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["vt_register_doc"][".buttonsAdded"] = false;
			tdataArray["vt_register_doc"][".addPageEvents"] = false;
			tdataArray["vt_register_doc"][".isUseTimeForSearch"] = false;
			tdataArray["vt_register_doc"][".badgeColor"] = "7B68EE";
			tdataArray["vt_register_doc"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_doc_id");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_doc_no");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_date");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_location_id");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_doc_owner");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_images");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_note");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("t_register_status");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("add_user");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("add_date");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("edit_user");
			tdataArray["vt_register_doc"][".googleLikeFields"].Add("edit_date");
			tdataArray["vt_register_doc"][".printerPageOrientation"] = 0;
			tdataArray["vt_register_doc"][".nPrinterPageScale"] = 100;
			tdataArray["vt_register_doc"][".nPrinterSplitRecords"] = 40;
			tdataArray["vt_register_doc"][".geocodingEnabled"] = false;
			tdataArray["vt_register_doc"][".isDisplayLoading"] = true;
			tdataArray["vt_register_doc"][".pageSize"] = 20;
			tdataArray["vt_register_doc"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["vt_register_doc"][".strOrderBy"] = tstrOrderBy;
			tdataArray["vt_register_doc"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["vt_register_doc"][".sqlHead"] = "";
			tdataArray["vt_register_doc"][".sqlFrom"] = "";
			tdataArray["vt_register_doc"][".sqlWhereExpr"] = "";
			tdataArray["vt_register_doc"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["vt_register_doc"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["vt_register_doc"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["vt_register_doc"][".highlightSearchResults"] = true;
			tableKeysArray["vt_register_doc"] = SettingsMap.GetArray();
			tableKeysArray["vt_register_doc"].Add("t_register_doc_id");
			tableKeysArray["vt_register_doc"].Add("t_register_doc_no");
			tdataArray["vt_register_doc"][".Keys"] = tableKeysArray["vt_register_doc"];
			tdataArray["vt_register_doc"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "t_register_doc_id";
			fdata["GoodName"] = "t_register_doc_id";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_doc_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_doc_id";
			fdata["FullName"] = "t_register_doc_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_doc_id"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_doc_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "t_register_doc_no";
			fdata["GoodName"] = "t_register_doc_no";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_doc_no");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_doc_no";
			fdata["FullName"] = "t_register_doc_no";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_doc_no"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_doc_no");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "t_register_date";
			fdata["GoodName"] = "t_register_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "t_register_date";
			fdata["FullName"] = "t_register_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 2;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_date"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "t_register_location_id";
			fdata["GoodName"] = "t_register_location_id";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_location_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_location_id";
			fdata["FullName"] = "t_register_location_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_location_id"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_location_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "t_register_doc_owner";
			fdata["GoodName"] = "t_register_doc_owner";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_doc_owner");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_doc_owner";
			fdata["FullName"] = "t_register_doc_owner";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_doc_owner"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_doc_owner");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "t_register_images";
			fdata["GoodName"] = "t_register_images";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_images");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_images";
			fdata["FullName"] = "t_register_images";
			fdata["DeleteAssociatedFile"] = true;
			fdata["CompatibilityMode"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "File-based Image");
			vdata["ShowThumbnail"] = true;
			vdata["ThumbWidth"] = 200;
			vdata["ThumbHeight"] = 150;
			vdata["ImageWidth"] = 300;
			vdata["ImageHeight"] = 100;
			vdata["multipleImgMode"] = 1;
			vdata["maxImages"] = 1;
			vdata["showGallery"] = true;
			vdata["galleryMode"] = 2;
			vdata["captionMode"] = 2;
			vdata["captionField"] = "";
			vdata["imageBorder"] = 1;
			vdata["imageFullWidth"] = 1;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Document upload");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_images"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_images");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "t_register_note";
			fdata["GoodName"] = "t_register_note";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_note");
			fdata["FieldType"] = 202;
			fdata["strField"] = "t_register_note";
			fdata["FullName"] = "t_register_note";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_note"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_note");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "t_register_status";
			fdata["GoodName"] = "t_register_status";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","t_register_status");
			fdata["FieldType"] = 3;
			fdata["strField"] = "t_register_status";
			fdata["FullName"] = "t_register_status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["t_register_status"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("t_register_status");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "add_user";
			fdata["GoodName"] = "add_user";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","add_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "add_user";
			fdata["FullName"] = "add_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["add_user"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("add_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "add_date";
			fdata["GoodName"] = "add_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","add_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "add_date";
			fdata["FullName"] = "add_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["add_date"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("add_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "edit_user";
			fdata["GoodName"] = "edit_user";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","edit_user");
			fdata["FieldType"] = 202;
			fdata["strField"] = "edit_user";
			fdata["FullName"] = "edit_user";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["edit_user"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("edit_user");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "edit_date";
			fdata["GoodName"] = "edit_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("vt_register_doc","edit_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "edit_date";
			fdata["FullName"] = "edit_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["vt_register_doc"]["edit_date"] = fdata;
			tdataArray["vt_register_doc"][".searchableFields"].Add("edit_date");
			GlobalVars.tables_data["vt_register_doc"] = tdataArray["vt_register_doc"];
			GlobalVars.field_labels["vt_register_doc"] = fieldLabelsArray["vt_register_doc"];
			GlobalVars.fieldToolTips["vt_register_doc"] = fieldToolTipsArray["vt_register_doc"];
			GlobalVars.placeHolders["vt_register_doc"] = placeHoldersArray["vt_register_doc"];
			GlobalVars.page_titles["vt_register_doc"] = pageTitlesArray["vt_register_doc"];
			CommonFunctions.changeTextControlsToDate(new XVar("vt_register_doc"));
			GlobalVars.detailsTablesData["vt_register_doc"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["vt_register_doc"] = SettingsMap.GetArray();

				
		
			tdataArray["vt_register_doc"][".sqlquery"] = queryData_Array["vt_register_doc"];
			tdataArray["vt_register_doc"][".hasEvents"] = true;
			GlobalVars.tables_data["vt_register_doc"] = tdataArray["vt_register_doc"];
		}
	}

}
